#pragma once
/*
 * apple_ii_system.h — Apple II family system declaration
 *
 * Apple II (1977), Apple IIe (1983), Apple IIc (1984).
 * All are 6502/65C02-based with soft-switch video generation.
 *
 * Apple II:
 *   - MOS 6502 @ 1.023 MHz
 *   - 48KB RAM (max), 12KB ROM (Integer/Applesoft BASIC + Monitor)
 *   - 40×24 text, 280×192 hi-res, 40×48 lo-res — all soft-switch controlled
 *   - 1-bit speaker toggle, no sound chip
 *   - 8 expansion slots
 *
 * Apple IIe:
 *   - WDC 65C02 @ 1.023 MHz
 *   - 128KB RAM (64KB + 64KB auxiliary), 16KB ROM
 *   - 80-column text, double hi-res (560×192)
 *   - Same 1-bit speaker, same soft-switch video
 *
 * Apple IIc:
 *   - WDC 65C02 @ 1.023 MHz
 *   - 128KB RAM, 32KB ROM
 *   - Same display modes as IIe
 *   - Built-in 5.25" floppy, serial ports
 *
 * Memory map (48K Apple II):
 *   $0000–$BFFF : 48KB RAM (zero page, stack, text/hires pages)
 *   $C000–$C0FF : Soft switches (keyboard, speaker, display mode, I/O)
 *   $C100–$C7FF : Expansion slot I/O space (7 slots × 256 bytes)
 *   $C800–$CFFF : Shared expansion ROM space
 *   $D000–$FFFF : ROM (BASIC + Monitor)
 */

#include "systems/apple_ii/apple_ii_constants.hpp"
#include "core/system.hpp"
#include "core/system_lines.hpp"
#include "core/board.hpp"
#include "chip/cpu/fam65xx/mos6502.hpp"
#include "chip/cpu/fam65xx/wdc65c02.hpp"
#include "chip/memory/memory_chip.hpp"
#include <cstdint>

// ============================================================================
// Apple II Variant Template
// ============================================================================

enum class AppleIIVariant { APPLE_II, APPLE_IIE, APPLE_IIC };

template<AppleIIVariant V> struct AppleIIVariantTraits;

template<> struct AppleIIVariantTraits<AppleIIVariant::APPLE_II> {
    static constexpr const char* name         = "Apple II";
    static constexpr const char* short_name   = "AppleII";
    static constexpr const char* description  = "Apple II (1977) — MOS 6502, 48KB RAM, soft-switch video";
    static constexpr const char* data_folder  = "apple_ii";
    static constexpr uint32_t    ram_size     = apple_ii_constants::RAM_48K;
    static constexpr uint16_t    rom_size     = apple_ii_constants::ROM_SIZE_12K;
    static constexpr uint16_t    rom_start    = 0xD000;
    static constexpr bool        has_80col    = false;
    static constexpr bool        has_aux_mem  = false;
    static constexpr bool        is_cmos      = false;
    static std::vector<const char*> get_aliases() {
        return {"AppleII", "Apple 2", "Apple2", "Apple][", "A2"};
    }
};

template<> struct AppleIIVariantTraits<AppleIIVariant::APPLE_IIE> {
    static constexpr const char* name         = "Apple IIe";
    static constexpr const char* short_name   = "AppleIIe";
    static constexpr const char* description  = "Apple IIe (1983) — 65C02, 128KB, 80-col, double hi-res";
    static constexpr const char* data_folder  = "apple_ii";
    static constexpr uint32_t    ram_size     = apple_ii_constants::RAM_128K;
    static constexpr uint16_t    rom_size     = apple_ii_constants::ROM_SIZE_16K;
    static constexpr uint16_t    rom_start    = 0xC000;
    static constexpr bool        has_80col    = true;
    static constexpr bool        has_aux_mem  = true;
    static constexpr bool        is_cmos      = true;
    static std::vector<const char*> get_aliases() {
        return {"AppleIIe", "Apple IIe", "Apple2e", "A2e"};
    }
};

template<> struct AppleIIVariantTraits<AppleIIVariant::APPLE_IIC> {
    static constexpr const char* name         = "Apple IIc";
    static constexpr const char* short_name   = "AppleIIc";
    static constexpr const char* description  = "Apple IIc (1984) — 65C02, 128KB, built-in floppy, portable";
    static constexpr const char* data_folder  = "apple_ii";
    static constexpr uint32_t    ram_size     = apple_ii_constants::RAM_128K;
    static constexpr uint16_t    rom_size     = apple_ii_constants::ROM_SIZE_16K;
    static constexpr uint16_t    rom_start    = 0xC000;
    static constexpr bool        has_80col    = true;
    static constexpr bool        has_aux_mem  = true;
    static constexpr bool        is_cmos      = true;
    static std::vector<const char*> get_aliases() {
        return {"AppleIIc", "Apple IIc", "Apple2c", "A2c"};
    }
};

// ============================================================================
// Apple II chip manifests — declarative memory layout
// ============================================================================
//
// Video is generated by software from RAM contents — no video chip.
// I/O is handled via soft switches at $C000-$C0FF in the system tick.
// Speaker is a 1-bit toggle at $C030 — no sound chip.
//
// Apple II (48K):
//   Slot 0: RAM  — 48 KB at $0000
//   Slot 1: ROM  — 12 KB at $D000 (Applesoft BASIC + Monitor)
//
// Apple IIe/IIc (128K):
//   Slot 0: RAM  — 128 KB at $0000 (main 64KB + aux 64KB, bank-switched)
//   Slot 1: ROM  — 16 KB at $C000
//
// Soft switches at $C000-$C0FF are implemented in the system tick, not the bus.
//

#define APPLE_II_BUS_DEFAULT_STATE (MOS6502::default_bus_state())

// Apple II (original, 48K)
// RAM split into 32KB + 16KB (sizes must be power-of-2).
// ROM extended to 16KB at $C000 — soft switches at $C000-$C0FF handled in tick.
// Character ROM not bus-mapped — loaded manually in initialize().
inline constexpr auto kAppleIIChips = make_chip_manifest(
    Slot<RAMChip>{0x0000, 32768, 0, "Main RAM"},       // $0000-$7FFF
    Slot<RAMChip>{0x8000, 16384, 0, "Upper RAM"},       // $8000-$BFFF
    Slot<ROMChip>{0xC000, 16384, 0, "ROM"}.with_rom("apple2.rom|APPLE2.ROM|apple2o.rom"),
    Slot<MOS6502>{0, 0, 0, "MOS 6502"}
);

// Apple IIe (128K, 65C02)
// Character ROM not bus-mapped — loaded manually in initialize().
inline constexpr auto kAppleIIeChips = make_chip_manifest(
    Slot<RAMChip>{0x0000, 131072, 0, "RAM", 0, 65536},  // 2 × 64KB banks
    Slot<ROMChip>{0xC000, 16384, 0, "ROM"}.with_rom("apple2e.rom|APPLE2E.ROM|apple2e_enhanced.rom"),
    Slot<WDC_65C02>{0, 0, 0, "WDC 65C02"}
);

// Apple IIc (128K, 65C02, same layout as IIe)
// Character ROM not bus-mapped — loaded manually in initialize().
inline constexpr auto kAppleIIcChips = make_chip_manifest(
    Slot<RAMChip>{0x0000, 131072, 0, "RAM", 0, 65536},
    Slot<ROMChip>{0xC000, 32768, 0, "ROM", 0, 16384}.with_rom("apple2c.rom|APPLE2C.ROM|apple2c_v4.rom"),
    Slot<WDC_65C02>{0, 0, 0, "WDC 65C02"}
);

// BusTraits — selects the correct manifest per variant
template<AppleIIVariant V> struct AppleIIBusTraits;

template<> struct AppleIIBusTraits<AppleIIVariant::APPLE_II> {
    static constexpr const auto& kManifest = kAppleIIChips;
    using Spec = ManifestBusSpec<kAppleIIChips, 16, 8>;
};

template<> struct AppleIIBusTraits<AppleIIVariant::APPLE_IIE> {
    static constexpr const auto& kManifest = kAppleIIeChips;
    using Spec = ManifestBusSpec<kAppleIIeChips, 16, 8>;
};

template<> struct AppleIIBusTraits<AppleIIVariant::APPLE_IIC> {
    static constexpr const auto& kManifest = kAppleIIcChips;
    using Spec = ManifestBusSpec<kAppleIIcChips, 16, 8>;
};

// ============================================================================
// Apple II System
// ============================================================================

template<AppleIIVariant V>
class AppleIISystem : public System {
    using Traits = AppleIIVariantTraits<V>;
    using BTraits = AppleIIBusTraits<V>;

public:
    AppleIISystem();
    ~AppleIISystem() override;

    // ── System interface ─────────────────────────────────────────
    const SystemDescriptor& get_descriptor() const override;
    bool set_configuration(const SystemConfiguration& config) override;
    bool apply_configuration() override;

    bool initialize() override;
    void shutdown() override;
    void reset() override;

    void tick() override;
    void run_frame() override;

    bool load_file(const char* filepath) override;

    void get_display_dimensions(int* width, int* height) const override;

    uint32_t get_audio_samples(float* buffer, uint32_t max_samples) override;
    void set_audio_sample_rate(int sample_rate_hz) override;

    void handle_keyboard_event(SDL_Keycode key, bool pressed) override;
    void handle_text_input(const char* text) override;
    void render_system_menu_items() override;
    void render_configuration_ui() override;
    void set_speed_multiplier(float multiplier) override;

    bool is_system_ready() const override { return system_ready_; }

private:
    // ── Chips ────────────────────────────────────────────────────────────
    // CPU type depends on variant (MOS6502 for II, WDC65C02 for IIe/IIc)
    // Both are accessed via ChipBase* through the board.
    ChipBase*  cpu_chip_ = nullptr;

    // ── Memory chips — post-init pointers ────────────────────────────────
    ROMChip* rom_       = nullptr;
    uint8_t* ram_ptr_   = nullptr;   // Direct pointer for soft-switch video rendering

    // ── Board + bus ──────────────────────────────────────────────────────
    using Bus       = MemoryBus<typename BTraits::Spec>;
    using MainBoard = Board<typename BTraits::Spec>;
    Bus       bus_;
    MainBoard board_{BTraits::kManifest};

    // ── Display ──────────────────────────────────────────────────────────
    IndexedFrameBuffer display_;

    // ── Soft switch state ────────────────────────────────────────────────
    bool    sw_text_     = true;     // Text/Graphics mode
    bool    sw_mixed_    = false;    // Mixed text+graphics
    bool    sw_page2_    = false;    // Display page select
    bool    sw_hires_    = false;    // Hi-res / Lo-res
    bool    sw_80col_    = false;    // 80-column mode (IIe/IIc only)
    bool    sw_altchar_  = false;    // Alternate character set (IIe/IIc only)

    // ── Memory banking (IIe/IIc) ────────────────────────────────────────
    bool    sw_auxmem_   = false;    // Auxiliary memory read
    bool    sw_auxwrite_ = false;    // Auxiliary memory write
    bool    sw_lcram_    = false;    // Language card RAM enable
    bool    sw_lcwrite_  = false;    // Language card write enable
    bool    sw_lcbank2_  = false;    // Language card bank 2 select

    // ── Keyboard ─────────────────────────────────────────────────────────
    uint8_t kbd_data_    = 0;        // Last key, bit 7 = strobe
    bool    kbd_strobe_  = false;

    // ── Speaker ──────────────────────────────────────────────────────────
    bool    spkr_state_  = false;    // Current speaker level
    int     audio_sample_rate_ = apple_ii_constants::DEFAULT_SAMPLE_RATE;

    // ── System state ─────────────────────────────────────────────────────
    bus_state_t pins_      = APPLE_II_BUS_DEFAULT_STATE;
    bool        system_ready_ = false;

    // ── Internal helpers ─────────────────────────────────────────────────
    void configure_bus_memory_map();
    void render_frame();
    bool load_roms();
    uint8_t soft_switch_read(uint16_t addr);
    void    soft_switch_write(uint16_t addr, uint8_t data);
};
