#pragma once
/*
 * apple_ii_system.h — Apple II family system declaration
 *
 * Apple II (1977), Apple IIe (1983), Apple IIc (1984).
 * All are 6502/65C02-based with soft-switch video generation.
 *
 * Apple II:
 *   - MOS 6502 @ 1.023 MHz
 *   - 48KB RAM (max), 12KB ROM (Integer/Applesoft BASIC + Monitor)
 *   - 40×24 text, 280×192 hi-res, 40×48 lo-res — all soft-switch controlled
 *   - 1-bit speaker toggle, no sound chip
 *   - 8 expansion slots
 *
 * Apple IIe:
 *   - WDC 65C02 @ 1.023 MHz
 *   - 128KB RAM (64KB + 64KB auxiliary), 16KB ROM
 *   - 80-column text, double hi-res (560×192)
 *   - Same 1-bit speaker, same soft-switch video
 *
 * Apple IIc:
 *   - WDC 65C02 @ 1.023 MHz
 *   - 128KB RAM, 32KB ROM
 *   - Same display modes as IIe
 *   - Built-in 5.25" floppy, serial ports
 *
 * Memory map (48K Apple II):
 *   $0000–$BFFF : 48KB RAM (zero page, stack, text/hires pages)
 *   $C000–$C0FF : Soft switches (keyboard, speaker, display mode, I/O)
 *   $C100–$C7FF : Expansion slot I/O space (7 slots × 256 bytes)
 *   $C800–$CFFF : Shared expansion ROM space
 *   $D000–$FFFF : ROM (BASIC + Monitor)
 */

#include "systems/apple_ii/apple_ii_constants.hpp"
#include "core/system.hpp"
#include "core/system_lines.hpp"
#include "core/board.hpp"
#include "core/typed_manifest.hpp"
#include "core/typed_port.hpp"
#include "core/signal/video_port.hpp"
#include "chip/cpu/fam65xx/mos6502.hpp"
#include "chip/cpu/fam65xx/wdc65c02.hpp"
#include "chip/memory/memory_chip.hpp"
#include <cstdint>

// ============================================================================
// Apple II Variant Template
// ============================================================================

enum class AppleIIVariant { APPLE_II, APPLE_IIE, APPLE_IIC };

template<AppleIIVariant V> struct AppleIIVariantTraits;

template<> struct AppleIIVariantTraits<AppleIIVariant::APPLE_II> {
    static constexpr const char* name         = "Apple II";
    static constexpr const char* short_name   = "AppleII";
    static constexpr const char* description  = "Apple II (1977) — MOS 6502, 48KB RAM, soft-switch video";
    static constexpr const char* data_folder  = "apple_ii";
    static constexpr uint32_t    ram_size     = apple_ii_constants::RAM_48K;
    static constexpr uint16_t    rom_size     = apple_ii_constants::ROM_SIZE_12K;
    static constexpr uint16_t    rom_start    = 0xD000;
    static constexpr bool        has_80col    = false;
    static constexpr bool        has_aux_mem  = false;
    static constexpr bool        is_cmos      = false;
    static std::vector<const char*> get_aliases() {
        return {"AppleII", "Apple 2", "Apple2", "Apple][", "A2"};
    }
};

template<> struct AppleIIVariantTraits<AppleIIVariant::APPLE_IIE> {
    static constexpr const char* name         = "Apple IIe";
    static constexpr const char* short_name   = "AppleIIe";
    static constexpr const char* description  = "Apple IIe (1983) — 65C02, 128KB, 80-col, double hi-res";
    static constexpr const char* data_folder  = "apple_ii";
    static constexpr uint32_t    ram_size     = apple_ii_constants::RAM_128K;
    static constexpr uint16_t    rom_size     = apple_ii_constants::ROM_SIZE_16K;
    static constexpr uint16_t    rom_start    = 0xC000;
    static constexpr bool        has_80col    = true;
    static constexpr bool        has_aux_mem  = true;
    static constexpr bool        is_cmos      = true;
    static std::vector<const char*> get_aliases() {
        return {"AppleIIe", "Apple IIe", "Apple2e", "A2e"};
    }
};

template<> struct AppleIIVariantTraits<AppleIIVariant::APPLE_IIC> {
    static constexpr const char* name         = "Apple IIc";
    static constexpr const char* short_name   = "AppleIIc";
    static constexpr const char* description  = "Apple IIc (1984) — 65C02, 128KB, built-in floppy, portable";
    static constexpr const char* data_folder  = "apple_ii";
    static constexpr uint32_t    ram_size     = apple_ii_constants::RAM_128K;
    static constexpr uint16_t    rom_size     = apple_ii_constants::ROM_SIZE_16K;
    static constexpr uint16_t    rom_start    = 0xC000;
    static constexpr bool        has_80col    = true;
    static constexpr bool        has_aux_mem  = true;
    static constexpr bool        is_cmos      = true;
    static std::vector<const char*> get_aliases() {
        return {"AppleIIc", "Apple IIc", "Apple2c", "A2c"};
    }
};

// ============================================================================
// Apple II chip manifests — declarative memory layout
// ============================================================================
//
// Video is generated by software from RAM contents — no video chip.
// I/O is handled via soft switches at $C000-$C0FF in the system tick.
// Speaker is a 1-bit toggle at $C030 — no sound chip.
//
// Apple II (48K):
//   Slot 0: RAM  — 48 KB at $0000
//   Slot 1: ROM  — 12 KB at $D000 (Applesoft BASIC + Monitor)
//
// Apple IIe/IIc (128K):
//   Slot 0: RAM  — 128 KB at $0000 (main 64KB + aux 64KB, bank-switched)
//   Slot 1: ROM  — 16 KB at $C000
//
// Soft switches at $C000-$C0FF are implemented in the system tick, not the bus.
//

#define APPLE_II_BUS_DEFAULT_STATE (MOS6502::default_bus_state())

// Apple II (original, 48K)
// RAM split into 32KB + 16KB (sizes must be power-of-2).
// ROM extended to 16KB at $C000 — soft switches at $C000-$C0FF handled in tick.
// Character ROM not bus-mapped — loaded manually in initialize().
inline constexpr auto kAppleIIManifest = make_manifest(
    // Chips
    Slot<MOS6502>{.base_addr = 0, .label = "MOS 6502"},
    Slot<RAMChip>{.base_addr = 0x0000, .size_bytes = 32768, .label = "Main RAM"},
    Slot<RAMChip>{.base_addr = 0x8000, .size_bytes = 16384, .label = "Upper RAM"},
    Slot<ROMChip>{.base_addr = 0xC000, .size_bytes = 16384, .label = "ROM", .rom = {"apple2.rom|APPLE2.ROM|apple2o.rom"}},
    // Ports
    Slot<PortCassette>{.name = "Cassette Port"},
    Slot<PortExpansion>{.name = "Expansion Slots"},
    Slot<PortCompositeVideo>{.name = "Video Out", .default_device = "crt_tv"}
);

// Apple IIe (128K, 65C02)
// Character ROM not bus-mapped — loaded manually in initialize().
inline constexpr auto kAppleIIeManifest = make_manifest(
    // Chips
    Slot<WDC_65C02>{.base_addr = 0, .label = "WDC 65C02"},
    Slot<RAMChip>{.base_addr = 0x0000, .size_bytes = 131072, .label = "RAM", .bank_size = 65536},
    Slot<ROMChip>{.base_addr = 0xC000, .size_bytes = 16384, .label = "ROM", .rom = {"apple2e.rom|APPLE2E.ROM|apple2e_enhanced.rom"}},
    // Ports
    Slot<PortCassette>{.name = "Cassette Port"},
    Slot<PortExpansion>{.name = "Expansion Slots"},
    Slot<PortCompositeVideo>{.name = "Video Out", .default_device = "crt_tv"}
);

// Apple IIc (128K, 65C02, same layout as IIe)
// Character ROM not bus-mapped — loaded manually in initialize().
inline constexpr auto kAppleIIcManifest = make_manifest(
    // Chips
    Slot<WDC_65C02>{.base_addr = 0, .label = "WDC 65C02"},
    Slot<RAMChip>{.base_addr = 0x0000, .size_bytes = 131072, .label = "RAM", .bank_size = 65536},
    Slot<ROMChip>{.base_addr = 0xC000, .size_bytes = 32768, .label = "ROM", .bank_size = 16384, .rom = {"apple2c.rom|APPLE2C.ROM|apple2c_v4.rom"}},
    // Ports
    Slot<PortCassette>{.name = "Cassette Port"},
    Slot<PortExpansion>{.name = "Expansion Slots"},
    Slot<PortCompositeVideo>{.name = "Video Out", .default_device = "crt_tv"}
);

inline constexpr size_t kAppleIIChipCount  = decltype(kAppleIIManifest)::chip_count;
inline constexpr size_t kAppleIIeChipCount = decltype(kAppleIIeManifest)::chip_count;
inline constexpr size_t kAppleIIcChipCount = decltype(kAppleIIcManifest)::chip_count;

// BusTraits — selects the correct manifest per variant
template<AppleIIVariant V> struct AppleIIBusTraits;

template<> struct AppleIIBusTraits<AppleIIVariant::APPLE_II> {
    static constexpr const auto& kManifest = kAppleIIManifest;
    using Spec = ManifestBusSpec<kAppleIIManifest, 16, 8>;
};

template<> struct AppleIIBusTraits<AppleIIVariant::APPLE_IIE> {
    static constexpr const auto& kManifest = kAppleIIeManifest;
    using Spec = ManifestBusSpec<kAppleIIeManifest, 16, 8>;
};

template<> struct AppleIIBusTraits<AppleIIVariant::APPLE_IIC> {
    static constexpr const auto& kManifest = kAppleIIcManifest;
    using Spec = ManifestBusSpec<kAppleIIcManifest, 16, 8>;
};

// ── Board specializations ──────────────────────────────────────────────
// CPU type varies per variant (MOS6502 vs WDC_65C02), so each
// variant needs its own Board specialization with the correct
// component tuple and aliases.

template<AppleIIVariant V> struct AppleIIBoard;

template<>
struct AppleIIBoard<AppleIIVariant::APPLE_II>
    : Board<AppleIIBusTraits<AppleIIVariant::APPLE_II>::Spec, NoChips> {
    using BT  = AppleIIBusTraits<AppleIIVariant::APPLE_II>;
    using CPU = MOS6502;
    using ComponentTuple = decltype(kAppleIIManifest)::component_tuple;
    ComponentTuple components_;

    MOS6502& cpu       = std::get<0>(components_);
    RAMChip& ram       = std::get<1>(components_);
    RAMChip& upper_ram = std::get<2>(components_);
    ROMChip& rom       = std::get<3>(components_);

    PortCassette&       cassette_port  = std::get<4>(components_);
    PortExpansion&      expansion_port = std::get<5>(components_);
    PortCompositeVideo& video_port     = std::get<6>(components_);

    template<size_t N>
    AppleIIBoard(const ChipManifest<N>& m) : Board<BT::Spec, NoChips>(m) {}
};

template<>
struct AppleIIBoard<AppleIIVariant::APPLE_IIE>
    : Board<AppleIIBusTraits<AppleIIVariant::APPLE_IIE>::Spec, NoChips> {
    using BT  = AppleIIBusTraits<AppleIIVariant::APPLE_IIE>;
    using CPU = WDC_65C02;
    using ComponentTuple = decltype(kAppleIIeManifest)::component_tuple;
    ComponentTuple components_;

    WDC_65C02& cpu = std::get<0>(components_);
    RAMChip&   ram = std::get<1>(components_);
    ROMChip&   rom = std::get<2>(components_);

    PortCassette&       cassette_port  = std::get<3>(components_);
    PortExpansion&      expansion_port = std::get<4>(components_);
    PortCompositeVideo& video_port     = std::get<5>(components_);

    template<size_t N>
    AppleIIBoard(const ChipManifest<N>& m) : Board<BT::Spec, NoChips>(m) {}
};

template<>
struct AppleIIBoard<AppleIIVariant::APPLE_IIC>
    : Board<AppleIIBusTraits<AppleIIVariant::APPLE_IIC>::Spec, NoChips> {
    using BT  = AppleIIBusTraits<AppleIIVariant::APPLE_IIC>;
    using CPU = WDC_65C02;
    using ComponentTuple = decltype(kAppleIIcManifest)::component_tuple;
    ComponentTuple components_;

    WDC_65C02& cpu = std::get<0>(components_);
    RAMChip&   ram = std::get<1>(components_);
    ROMChip&   rom = std::get<2>(components_);

    PortCassette&       cassette_port  = std::get<3>(components_);
    PortExpansion&      expansion_port = std::get<4>(components_);
    PortCompositeVideo& video_port     = std::get<5>(components_);

    template<size_t N>
    AppleIIBoard(const ChipManifest<N>& m) : Board<BT::Spec, NoChips>(m) {}
};

// ============================================================================
// Apple II System
// ============================================================================

template<AppleIIVariant V>
class AppleIISystem : public System {
    using Traits = AppleIIVariantTraits<V>;
    using BTraits = AppleIIBusTraits<V>;

public:
    AppleIISystem();
    ~AppleIISystem() override;

    // ── System interface ─────────────────────────────────────────
    const SystemDescriptor& get_descriptor() const override;
    bool set_configuration(const SystemConfiguration& config) override;
    bool apply_configuration() override;

    bool initialize() override;
    void shutdown() override;
    void reset() override;

    void tick() override;
    void run_frame() override;

    bool load_file(const char* filepath) override;

    uint32_t get_audio_samples(float* buffer, uint32_t max_samples) override;
    void set_audio_sample_rate(int sample_rate_hz) override;

    void handle_keyboard_event(SDL_Keycode key, bool pressed) override;
    void handle_text_input(const char* text) override;

    void* get_video_port_ptr() override { return video_port_.get(); }

private:
    // ── Chips (value-typed via Board Chips) ────────────────────────────

    // ── Memory chips — post-init pointers ────────────────────────────────
    ROMChip* rom_       = nullptr;
    uint8_t* ram_ptr_   = nullptr;   // Direct pointer for soft-switch video rendering

    // ── Board + bus ──────────────────────────────────────────────────────
    using Bus       = MemoryBus<typename BTraits::Spec>;
    using MainBoard = AppleIIBoard<V>;
    Bus       bus_;
    MainBoard board_{BTraits::kManifest};

    // ── Display ──────────────────────────────────────────────────────────
    uint8_t pixel_buffer_[apple_ii_constants::DISPLAY_WIDTH * apple_ii_constants::DISPLAY_HEIGHT] = {};
    std::unique_ptr<CompositeVideoPort> video_port_;

    // ── Soft switch state ────────────────────────────────────────────────
    bool    sw_text_     = true;     // Text/Graphics mode
    bool    sw_mixed_    = false;    // Mixed text+graphics
    bool    sw_page2_    = false;    // Display page select
    bool    sw_hires_    = false;    // Hi-res / Lo-res
    bool    sw_80col_    = false;    // 80-column mode (IIe/IIc only)
    bool    sw_altchar_  = false;    // Alternate character set (IIe/IIc only)

    // ── Memory banking (IIe/IIc) ────────────────────────────────────────
    bool    sw_auxmem_   = false;    // Auxiliary memory read
    bool    sw_auxwrite_ = false;    // Auxiliary memory write
    bool    sw_lcram_    = false;    // Language card RAM enable
    bool    sw_lcwrite_  = false;    // Language card write enable
    bool    sw_lcbank2_  = false;    // Language card bank 2 select

    // ── Keyboard ─────────────────────────────────────────────────────────
    uint8_t kbd_data_    = 0;        // Last key, bit 7 = strobe
    bool    kbd_strobe_  = false;

    // ── Speaker ──────────────────────────────────────────────────────────
    bool    spkr_state_  = false;    // Current speaker level
    int     audio_sample_rate_ = apple_ii_constants::DEFAULT_SAMPLE_RATE;

    // ── System state ─────────────────────────────────────────────────────
    bus_state_t pins_      = APPLE_II_BUS_DEFAULT_STATE;

    // ── Internal helpers ─────────────────────────────────────────────────
    void configure_bus_memory_map();
    void render_frame();
    bool load_roms();
    uint8_t soft_switch_read(uint16_t addr);
    void    soft_switch_write(uint16_t addr, uint8_t data);
};
