#pragma once
// =============================================================================
// c64_manifest.hpp — C64 declarative chip manifest and bus configuration
// =============================================================================
//
// Defines the Commodore 64 chip memory layout for the manifest-driven
// Board<C64BusSpec> + MemoryBus<C64BusSpec> architecture.
//
// Buffer chips are ordered by size ascending for shift-addressable chip-id
// assignment (flat_mem offset = chip_id << 12, no table lookup):
//
//   CHARROM  4 KB  →  1 ID  → base_id =  0   Character ROM
//   ROML     8 KB  →  2 IDs → base_id =  1   Cartridge ROM Low
//   ROMH     8 KB  →  2 IDs → base_id =  3   Cartridge ROM High
//   BASIC    8 KB  →  2 IDs → base_id =  5   BASIC ROM
//   KERNAL   8 KB  →  2 IDs → base_id =  7   KERNAL ROM
//   RAM     64 KB  → 16 IDs → base_id =  9   Main RAM
//
// with_page_banking() sets bank_size=0 on all buffer chips so that each
// 4 KB page of a chip gets its own chip ID.  This enables the PLA to
// assign per-bank chip IDs directly into the page table.
//
// All buffer chips use overlay_group=1 so that apply() only populates
// chip_info (Phase 0) without mapping any pages (Phase 1).  Page tables
// are fully PLA-driven — each of the 32 banking modes is a ModeSnapshot
// that programs the correct chip at each 4 KB bank.
//
// I/O dispatch ($D000–$DFFF):
//   An IndexedSubTable with 4 bits (16 × 256 B entries) routes accesses
//   to MMIO handlers for VIC-II, SID, Color RAM, CIA1, CIA2, I/O1, I/O2.
//   In PLA modes where I/O is visible, page $D points to the sub-table
//   sentinel; in modes with CHARROM or RAM, it points to the buffer chip.
//
// =============================================================================

#include "core/chip_manifest.hpp"
#include "core/memory_bus/configs.hpp"
#include "core/board.hpp"
#include "core/system_chip_visitors.hpp"
#include "chip/memory/memory_chip.hpp"
#include "chip/cpu/fam65xx/mos6510.hpp"
#include "chip/video/vic_ii/vicii_common.hpp"
#include "chip/sound/mos6581.hpp"
#include "chip/memory/mos2114.hpp"
#include "chip/io/mos6526.hpp"


// =============================================================================
// §1  C64 Chip Declaration — Single Source of Truth
// =============================================================================
//
// Every C64 chip is declared exactly once in this macro.  All derived
// artifacts — manifest, chipset fields, binding, info tables — are
// generated by applying visitor macros to this list.
//
// Row arguments:
//   X(ctx, type, chip, base, size, overlay, label, info_label, rom_files)
//
// All chips become value-typed fields in C64Chipset.  Buffer vs MMIO is
// implicit: chips with size > 0 get a flat-memory buffer allocation;
// chips with size == 0 are MMIO-only.  Board::bind_chip() auto-calls
// on_bind_buffer() for buffer chips (MemoryChipBase overrides this).
//
// Buffer-backed chips MUST be ordered by size ascending (smallest first)
// for shift-addressable chip-id assignment.  MMIO chip order is flexible.
//

#define C64_FOR_EACH_SYSTEM_CHIP(X, ctx)                                                                           \
    /* ── Buffer-backed chips (PLA-switched, size ascending) ────────────────────────────────────────────────── */ \
    X(ctx, ROMChip,       charrom,   0xD000,  4096, 1, "CHARROM",     "Character ROM",                             \
        "C64 - 901225-01 - Commodore (EC4272EE) Characters.rom|"                                                   \
        "characters.901225-01.bin|901225-01.bin|chargen.rom|char.rom")                                             \
    X(ctx, ROMChip,       roml,      0x8000,  8192, 1, "ROML",        "Cartridge ROM Low",    nullptr)             \
    X(ctx, ROMChip,       romh,      0xA000,  8192, 1, "ROMH",        "Cartridge ROM High",   nullptr)             \
    X(ctx, ROMChip,       basic,     0xA000,  8192, 1, "BASIC ROM",   "BASIC ROM",                                 \
        "C64 - 901226-01 - Commodore (F833D117) Basic.rom|"                                                        \
        "basic.901226-01.bin|901226-01.bin|basic.rom")                                                             \
    X(ctx, ROMChip,       kernal,    0xE000,  8192, 1, "KERNAL",      "KERNAL ROM",                                \
        "C64 - 901227-03 - Commodore (DBE3E7C7) Kernal.rom|"                                                       \
        "kernal.901227-03.bin|901227-03.bin|kernal.rom")                                                           \
    X(ctx, RAMChip,       ram,       0x0000, 65536, 1, "RAM",         "RAM",                  nullptr)             \
    /* ── MMIO chips (no flat-memory buffer, I/O addresses for documentation) ─────────────────────────────── */   \
    X(ctx, MOS6510,       cpu,       0x0000,     0, 0, "MOS 6510",    "MOS 6510",             nullptr)             \
    X(ctx, vicii_base_t,  vicii,     0xD000,     0, 0, "VIC-II",      "VIC-II",               nullptr)             \
    X(ctx, mos6581_t,     sid,       0xD400,     0, 0, "SID",         "SID",                  nullptr)             \
    X(ctx, MOS2114,       colorram,  0xD800,     0, 0, "Color RAM",   "Color RAM",            nullptr)             \
    X(ctx, mos6526_t,     cia1,      0xDC00,     0, 0, "CIA1",        "CIA1",                 nullptr)             \
    X(ctx, mos6526_t,     cia2,      0xDD00,     0, 0, "CIA2",        "CIA2",                 nullptr)

// Total chip count (auto-derived from macro)
static constexpr size_t kC64ChipCount = 0 C64_FOR_EACH_SYSTEM_CHIP(CERMU_CHIP_VISITOR_COUNT_ONE, unused);


// =============================================================================
// §2  Chip Manifest (generated from C64_FOR_EACH_SYSTEM_CHIP)
// =============================================================================
//
// with_page_banking() sets bank_size=0 on all buffer chips so that each
// 4 KB page gets its own chip ID.  This enables per-bank chip-id assignment
// in the PLA page tables and activates the shift-addressable optimization.
//

inline constexpr ChipManifest<kC64ChipCount> kC64Chips = ChipManifest<kC64ChipCount>{{
    C64_FOR_EACH_SYSTEM_CHIP(CERMU_CHIP_VISITOR_MANIFEST_ROW, unused)
}}.with_page_banking();

// =============================================================================
// §3  Type Aliases
// =============================================================================

using C64Bus      = MemoryBus<C64BusSpec>;
using C64Board    = Board<C64BusSpec>;
using C64Snapshot = C64Bus::Snapshot;
using C64PT       = PackingTraits<C64BusSpec>;
using C64ChipId   = C64PT::ChipId;      // MemoryBus read-side chip/bank ID
using C64WriteId  = C64PT::WriteChipId;  // MemoryBus write-side chip/bank ID

// PLA output chip identifier — superset of MemoryBus buffer base_ids
// (0, 1, 3, 5, 7, 9) plus PLA-specific sentinels (kIo=0xFE, kUnmapped=0xFF).
using C64PlaChipId = uint8_t;

// =============================================================================
// §3b  Chip IDs (constexpr, derived from manifest)
// =============================================================================
//
// Base chip IDs under the page-banking scheme.  Each buffer chip's base_id
// is the prefix sum of preceding chips' bank counts (size / 4096).
// With size-ascending order and page banking:
//   CHARROM=0, ROML=1, ROMH=3, BASIC=5, KERNAL=7, RAM=9
//

namespace c64_chip_ids {
    // find<ROMChip>(n) returns the nth ROMChip in manifest order:
    //   0=CHARROM, 1=ROML, 2=ROMH, 3=BASIC, 4=KERNAL
    inline constexpr C64ChipId kCharrom = C64ChipId(kC64Chips.base_id(kC64Chips.find<ROMChip>(),    12));  // 0
    inline constexpr C64ChipId kRoml    = C64ChipId(kC64Chips.base_id(kC64Chips.find<ROMChip>(1),   12));  // 1
    inline constexpr C64ChipId kRomh    = C64ChipId(kC64Chips.base_id(kC64Chips.find<ROMChip>(2),   12));  // 3
    inline constexpr C64ChipId kBasic   = C64ChipId(kC64Chips.base_id(kC64Chips.find<ROMChip>(3),   12));  // 5
    inline constexpr C64ChipId kKernal  = C64ChipId(kC64Chips.base_id(kC64Chips.find<ROMChip>(4),   12));  // 7
    inline constexpr C64ChipId kRam     = C64ChipId(kC64Chips.base_id(kC64Chips.find<RAMChip>(),    12));  // 9

    // Sentinel values for PLA outputs that don't map to buffer chips
    inline constexpr C64PlaChipId kIo       = 0xFE;  // I/O region ($D000-$DFFF)
    inline constexpr C64PlaChipId kUnmapped = 0xFF;  // Unmapped / open bus

    // Buffer-backed chip count (for iteration)
    inline constexpr size_t kBufferChipCount = kC64Chips.buffer_chip_count();
}

// Verify consistency between C64BusSpec and the manifest
static_assert(C64BusSpec::MaxChipId == kC64Chips.max_chip_id(12),
    "C64BusSpec::MaxChipId must match manifest total bank IDs - 1");
static_assert(C64BusSpec::ShiftAddressable == kC64Chips.has_shift_addressable_banks(12),
    "C64BusSpec::ShiftAddressable must match manifest");
static_assert(!C64BusSpec::ShiftAddressable || C64BusSpec::ShiftBankBits == kC64Chips.shift_bank_bits(12),
    "C64BusSpec::ShiftBankBits must match manifest");

// =============================================================================
// §3c  Per-bank chip-id lookup table
// =============================================================================
//
// Maps a (base_id, bank) pair to the exact per-bank chip_id:
//   chip_id = base_id + (bank & kC64ChipBankMask[base_id])
//
// The mask is (num_banks - 1) for each chip, stored at the base_id index.
// Non-base-id entries are never accessed.
//
// This correctly handles the VIC-II case where a chip appears at a different
// address than its CPU base_addr (e.g. CHARROM at VIC bank 1 instead of
// CPU bank $D): the low bits of the bank select the intra-chip page.
//

inline constexpr auto kC64ChipBankMask = []() {
    constexpr size_t page_bits = 12;
    constexpr size_t total = kC64Chips.total_ids(page_bits);
    std::array<uint8_t, total> table{};
    for (size_t i = 0; i < kC64ChipCount; ++i) {
        const auto& chip = kC64Chips.chips[i];
        if (chip.size_bytes == 0) continue;
        const size_t bid = kC64Chips.base_id(i, page_bits);
        const size_t nb = chip.size_bytes >> page_bits;
        const uint8_t mask = uint8_t(nb - 1);
        for (size_t b = 0; b < nb; ++b)
            table[bid + b] = mask;
    }
    return table;
}();

// =============================================================================
// §3d  Chip Display Helpers (PLA debug GUI)
// =============================================================================

// All PLA chip IDs that can appear in PLA tables (for legend/iteration)
inline constexpr C64PlaChipId kC64AllChipIds[] = {
    C64PlaChipId(c64_chip_ids::kRam),  C64PlaChipId(c64_chip_ids::kRoml),
    C64PlaChipId(c64_chip_ids::kRomh), C64PlaChipId(c64_chip_ids::kBasic),
    C64PlaChipId(c64_chip_ids::kKernal), C64PlaChipId(c64_chip_ids::kCharrom),
    c64_chip_ids::kIo, c64_chip_ids::kUnmapped
};
inline constexpr size_t kC64AllChipIdCount = sizeof(kC64AllChipIds) / sizeof(kC64AllChipIds[0]);

// Short chip name for display
inline const char* c64_chip_title(C64PlaChipId chip_id) {
    using namespace c64_chip_ids;
    switch (chip_id) {
        case kRam:      return "RAM";
        case kRoml:     return "ROML";
        case kRomh:     return "ROMH";
        case kBasic:    return "BASIC";
        case kKernal:   return "KERNAL";
        case kCharrom:  return "CHARROM";
        case kIo:       return "I/O";
        case kUnmapped: return "-";
        default:        return "?";
    }
}

// Chip descriptor for PLA debug tables
struct C64ChipInfo {
    uint16_t base;
    size_t   size;
    const char* label;
};

// Fetch display info for a PLA chip ID (base_id).  Returns true if valid.
inline bool c64_chip_info(C64PlaChipId chip_id, C64ChipInfo* out) {
    using namespace c64_chip_ids;
    // Info table generated from C64_FOR_EACH_SYSTEM_CHIP (all chips,
    // indexed by manifest slot position).  Buffer chips are matched by
    // base_id; MMIO entries are skipped.
    static constexpr C64ChipInfo kInfo[] = {
        C64_FOR_EACH_SYSTEM_CHIP(CERMU_CHIP_VISITOR_INFO_ROW, unused)
    };
    for (size_t i = 0; i < kC64ChipCount; ++i) {
        if (kC64Chips.chips[i].size_bytes > 0 &&
            kC64Chips.base_id(i, 12) == size_t(chip_id)) {
            *out = kInfo[i];
            return true;
        }
    }
    if (chip_id == kIo)       { *out = {0xD000, 4096, "I/O"};      return true; }
    if (chip_id == kUnmapped) { *out = {0,         0, "Unmapped"};  return true; }
    *out = {0, 0, "?"};
    return false;
}

// Number of PLA banking modes (5-bit: LORAM, HIRAM, CHAREN, EXROM, GAME)
inline constexpr size_t kC64NumPlaModes = 32;
