/*
 * AUTO-GENERATED by fam65xx_gen.py
 * 65xx Family CPU Decoder
 * Optimized for maximum performance and 100% hardware accuracy
 * 
 * Layout:
 *   [0-255]   : Opcode-specific cycles
 *   [256-293] : Shared addressing mode sequences
 *   [294-308]  : Shared continuation sequences
 * Total cases: 309
 */

// Continuation sequence indices:
// BRK: 294
// ASL_RMW: 295
// JSR: 296
// ROL_RMW: 297
// PLP: 298
// RTI: 299
// LSR_RMW: 300
// JMP_ABS: 301
// RTS: 302
// ROR_RMW: 303
// PLA: 304
// JMP_IND: 305
// BRANCH_TAKEN: 306
// DEC_RMW: 307
// INC_RMW: 308

// Addressing mode offset constants
// Offset 0 = direct opcode jump (no addressing mode)
// Other offsets use base correction of 255
#define ADDR_NONE       0   // Direct opcode execution (no addressing mode)
#define ADDR_IMM     1   // Index 256
#define ADDR_ZER     3   // Index 258
#define ADDR_ZPX     6   // Index 261
#define ADDR_ZPY     10  // Index 265
#define ADDR_ABS     14  // Index 269
#define ADDR_ABX     18  // Index 273
#define ADDR_ABY     23  // Index 278
#define ADDR_IDX     28  // Index 283
#define ADDR_IDY     34  // Index 289

// Lookup table: addressing mode start index for each opcode
static const uint8_t opcode_addr_start[256] = {
    ADDR_NONE,  // 0x00: BRK
    ADDR_IDX,  // 0x01: ORA
    ADDR_NONE,  // 0x02: JAM
    ADDR_IDX,  // 0x03: SLO
    ADDR_ZER,  // 0x04: NOP
    ADDR_ZER,  // 0x05: ORA
    ADDR_ZER,  // 0x06: ASL
    ADDR_ZER,  // 0x07: SLO
    ADDR_NONE,  // 0x08: PHP
    ADDR_IMM,  // 0x09: ORA
    ADDR_NONE,  // 0x0A: ASL
    ADDR_IMM,  // 0x0B: ANC
    ADDR_ABS,  // 0x0C: NOP
    ADDR_ABS,  // 0x0D: ORA
    ADDR_ABS,  // 0x0E: ASL
    ADDR_ABS,  // 0x0F: SLO
    ADDR_IMM,  // 0x10: BPL
    ADDR_IDY,  // 0x11: ORA
    ADDR_NONE,  // 0x12: JAM
    ADDR_IDY,  // 0x13: SLO
    ADDR_ZPX,  // 0x14: NOP
    ADDR_ZPX,  // 0x15: ORA
    ADDR_ZPX,  // 0x16: ASL
    ADDR_ZPX,  // 0x17: SLO
    ADDR_NONE,  // 0x18: CLC
    ADDR_ABY,  // 0x19: ORA
    ADDR_NONE,  // 0x1A: NOP
    ADDR_ABY,  // 0x1B: SLO
    ADDR_ABX,  // 0x1C: NOP
    ADDR_ABX,  // 0x1D: ORA
    ADDR_ABX,  // 0x1E: ASL
    ADDR_ABX,  // 0x1F: SLO
    ADDR_NONE,  // 0x20: JSR
    ADDR_IDX,  // 0x21: AND
    ADDR_NONE,  // 0x22: JAM
    ADDR_IDX,  // 0x23: RLA
    ADDR_ZER,  // 0x24: BIT
    ADDR_ZER,  // 0x25: AND
    ADDR_ZER,  // 0x26: ROL
    ADDR_ZER,  // 0x27: RLA
    ADDR_NONE,  // 0x28: PLP
    ADDR_IMM,  // 0x29: AND
    ADDR_NONE,  // 0x2A: ROL
    ADDR_IMM,  // 0x2B: ANC
    ADDR_ABS,  // 0x2C: BIT
    ADDR_ABS,  // 0x2D: AND
    ADDR_ABS,  // 0x2E: ROL
    ADDR_ABS,  // 0x2F: RLA
    ADDR_IMM,  // 0x30: BMI
    ADDR_IDY,  // 0x31: AND
    ADDR_NONE,  // 0x32: JAM
    ADDR_IDY,  // 0x33: RLA
    ADDR_ZPX,  // 0x34: NOP
    ADDR_ZPX,  // 0x35: AND
    ADDR_ZPX,  // 0x36: ROL
    ADDR_ZPX,  // 0x37: RLA
    ADDR_NONE,  // 0x38: SEC
    ADDR_ABY,  // 0x39: AND
    ADDR_NONE,  // 0x3A: NOP
    ADDR_ABY,  // 0x3B: RLA
    ADDR_ABX,  // 0x3C: NOP
    ADDR_ABX,  // 0x3D: AND
    ADDR_ABX,  // 0x3E: ROL
    ADDR_ABX,  // 0x3F: RLA
    ADDR_NONE,  // 0x40: RTI
    ADDR_IDX,  // 0x41: EOR
    ADDR_NONE,  // 0x42: JAM
    ADDR_IDX,  // 0x43: SRE
    ADDR_ZER,  // 0x44: NOP
    ADDR_ZER,  // 0x45: EOR
    ADDR_ZER,  // 0x46: LSR
    ADDR_ZER,  // 0x47: SRE
    ADDR_NONE,  // 0x48: PHA
    ADDR_IMM,  // 0x49: EOR
    ADDR_NONE,  // 0x4A: LSR
    ADDR_IMM,  // 0x4B: ASR
    ADDR_NONE,  // 0x4C: JMP
    ADDR_ABS,  // 0x4D: EOR
    ADDR_ABS,  // 0x4E: LSR
    ADDR_ABS,  // 0x4F: SRE
    ADDR_IMM,  // 0x50: BVC
    ADDR_IDY,  // 0x51: EOR
    ADDR_NONE,  // 0x52: JAM
    ADDR_IDY,  // 0x53: SRE
    ADDR_ZPX,  // 0x54: NOP
    ADDR_ZPX,  // 0x55: EOR
    ADDR_ZPX,  // 0x56: LSR
    ADDR_ZPX,  // 0x57: SRE
    ADDR_NONE,  // 0x58: CLI
    ADDR_ABY,  // 0x59: EOR
    ADDR_NONE,  // 0x5A: NOP
    ADDR_ABY,  // 0x5B: SRE
    ADDR_ABX,  // 0x5C: NOP
    ADDR_ABX,  // 0x5D: EOR
    ADDR_ABX,  // 0x5E: LSR
    ADDR_ABX,  // 0x5F: SRE
    ADDR_NONE,  // 0x60: RTS
    ADDR_IDX,  // 0x61: ADC
    ADDR_NONE,  // 0x62: JAM
    ADDR_IDX,  // 0x63: RRA
    ADDR_ZER,  // 0x64: NOP
    ADDR_ZER,  // 0x65: ADC
    ADDR_ZER,  // 0x66: ROR
    ADDR_ZER,  // 0x67: RRA
    ADDR_NONE,  // 0x68: PLA
    ADDR_IMM,  // 0x69: ADC
    ADDR_NONE,  // 0x6A: ROR
    ADDR_IMM,  // 0x6B: ARR
    ADDR_NONE,  // 0x6C: JMP
    ADDR_ABS,  // 0x6D: ADC
    ADDR_ABS,  // 0x6E: ROR
    ADDR_ABS,  // 0x6F: RRA
    ADDR_IMM,  // 0x70: BVS
    ADDR_IDY,  // 0x71: ADC
    ADDR_NONE,  // 0x72: JAM
    ADDR_IDY,  // 0x73: RRA
    ADDR_ZPX,  // 0x74: NOP
    ADDR_ZPX,  // 0x75: ADC
    ADDR_ZPX,  // 0x76: ROR
    ADDR_ZPX,  // 0x77: RRA
    ADDR_NONE,  // 0x78: SEI
    ADDR_ABY,  // 0x79: ADC
    ADDR_NONE,  // 0x7A: NOP
    ADDR_ABY,  // 0x7B: RRA
    ADDR_ABX,  // 0x7C: NOP
    ADDR_ABX,  // 0x7D: ADC
    ADDR_ABX,  // 0x7E: ROR
    ADDR_ABX,  // 0x7F: RRA
    ADDR_IMM,  // 0x80: NOP
    ADDR_IDX,  // 0x81: STA
    ADDR_IMM,  // 0x82: NOP
    ADDR_IDX,  // 0x83: SAX
    ADDR_ZER,  // 0x84: STY
    ADDR_ZER,  // 0x85: STA
    ADDR_ZER,  // 0x86: STX
    ADDR_ZER,  // 0x87: SAX
    ADDR_NONE,  // 0x88: DEY
    ADDR_IMM,  // 0x89: NOP
    ADDR_NONE,  // 0x8A: TXA
    ADDR_IMM,  // 0x8B: XAA
    ADDR_ABS,  // 0x8C: STY
    ADDR_ABS,  // 0x8D: STA
    ADDR_ABS,  // 0x8E: STX
    ADDR_ABS,  // 0x8F: SAX
    ADDR_IMM,  // 0x90: BCC
    ADDR_IDY,  // 0x91: STA
    ADDR_NONE,  // 0x92: JAM
    ADDR_IDY,  // 0x93: SHA
    ADDR_ZPX,  // 0x94: STY
    ADDR_ZPX,  // 0x95: STA
    ADDR_ZPY,  // 0x96: STX
    ADDR_ZPY,  // 0x97: SAX
    ADDR_NONE,  // 0x98: TYA
    ADDR_ABY,  // 0x99: STA
    ADDR_NONE,  // 0x9A: TXS
    ADDR_ABY,  // 0x9B: SHS
    ADDR_ABX,  // 0x9C: SHY
    ADDR_ABX,  // 0x9D: STA
    ADDR_ABY,  // 0x9E: SHX
    ADDR_ABY,  // 0x9F: SHY
    ADDR_IMM,  // 0xA0: LDY
    ADDR_IDX,  // 0xA1: LDA
    ADDR_IMM,  // 0xA2: LDX
    ADDR_IDX,  // 0xA3: LAX
    ADDR_ZER,  // 0xA4: LDY
    ADDR_ZER,  // 0xA5: LDA
    ADDR_ZER,  // 0xA6: LDX
    ADDR_ZER,  // 0xA7: LAX
    ADDR_NONE,  // 0xA8: TAY
    ADDR_IMM,  // 0xA9: LDA
    ADDR_NONE,  // 0xAA: TAX
    ADDR_IMM,  // 0xAB: LAX
    ADDR_ABS,  // 0xAC: LDY
    ADDR_ABS,  // 0xAD: LDA
    ADDR_ABS,  // 0xAE: LDX
    ADDR_ABS,  // 0xAF: LAX
    ADDR_IMM,  // 0xB0: BCS
    ADDR_IDY,  // 0xB1: LDA
    ADDR_NONE,  // 0xB2: JAM
    ADDR_IDY,  // 0xB3: LAX
    ADDR_ZPX,  // 0xB4: LDY
    ADDR_ZPX,  // 0xB5: LDA
    ADDR_ZPY,  // 0xB6: LDX
    ADDR_ZPY,  // 0xB7: LAX
    ADDR_NONE,  // 0xB8: CLV
    ADDR_ABY,  // 0xB9: LDA
    ADDR_NONE,  // 0xBA: TSX
    ADDR_ABY,  // 0xBB: LAS
    ADDR_ABX,  // 0xBC: LDY
    ADDR_ABX,  // 0xBD: LDA
    ADDR_ABY,  // 0xBE: LDX
    ADDR_ABY,  // 0xBF: LAX
    ADDR_IMM,  // 0xC0: CPY
    ADDR_IDX,  // 0xC1: CMP
    ADDR_IMM,  // 0xC2: NOP
    ADDR_IDX,  // 0xC3: DCP
    ADDR_ZER,  // 0xC4: CPY
    ADDR_ZER,  // 0xC5: CMP
    ADDR_ZER,  // 0xC6: DEC
    ADDR_ZER,  // 0xC7: DCP
    ADDR_NONE,  // 0xC8: INY
    ADDR_IMM,  // 0xC9: CMP
    ADDR_NONE,  // 0xCA: DEX
    ADDR_IMM,  // 0xCB: SBX
    ADDR_ABS,  // 0xCC: CPY
    ADDR_ABS,  // 0xCD: CMP
    ADDR_ABS,  // 0xCE: DEC
    ADDR_ABS,  // 0xCF: DCP
    ADDR_IMM,  // 0xD0: BNE
    ADDR_IDY,  // 0xD1: CMP
    ADDR_NONE,  // 0xD2: JAM
    ADDR_IDY,  // 0xD3: DCP
    ADDR_ZPX,  // 0xD4: NOP
    ADDR_ZPX,  // 0xD5: CMP
    ADDR_ZPX,  // 0xD6: DEC
    ADDR_ZPX,  // 0xD7: DCP
    ADDR_NONE,  // 0xD8: CLD
    ADDR_ABY,  // 0xD9: CMP
    ADDR_NONE,  // 0xDA: NOP
    ADDR_ABY,  // 0xDB: DCP
    ADDR_ABX,  // 0xDC: NOP
    ADDR_ABX,  // 0xDD: CMP
    ADDR_ABX,  // 0xDE: DEC
    ADDR_ABX,  // 0xDF: DCP
    ADDR_IMM,  // 0xE0: CPX
    ADDR_IDX,  // 0xE1: SBC
    ADDR_IMM,  // 0xE2: NOP
    ADDR_IDX,  // 0xE3: ISC
    ADDR_ZER,  // 0xE4: CPX
    ADDR_ZER,  // 0xE5: SBC
    ADDR_ZER,  // 0xE6: INC
    ADDR_ZER,  // 0xE7: ISC
    ADDR_NONE,  // 0xE8: INX
    ADDR_IMM,  // 0xE9: SBC
    ADDR_NONE,  // 0xEA: NOP
    ADDR_IMM,  // 0xEB: SBC
    ADDR_ABS,  // 0xEC: CPX
    ADDR_ABS,  // 0xED: SBC
    ADDR_ABS,  // 0xEE: INC
    ADDR_ABS,  // 0xEF: ISC
    ADDR_IMM,  // 0xF0: BEQ
    ADDR_IDY,  // 0xF1: SBC
    ADDR_NONE,  // 0xF2: JAM
    ADDR_IDY,  // 0xF3: ISC
    ADDR_ZPX,  // 0xF4: NOP
    ADDR_ZPX,  // 0xF5: SBC
    ADDR_ZPX,  // 0xF6: INC
    ADDR_ZPX,  // 0xF7: ISC
    ADDR_NONE,  // 0xF8: SED
    ADDR_ABY,  // 0xF9: SBC
    ADDR_NONE,  // 0xFA: NOP
    ADDR_ABY,  // 0xFB: ISC
    ADDR_ABX,  // 0xFC: NOP
    ADDR_ABX,  // 0xFD: SBC
    ADDR_ABX,  // 0xFE: INC
    ADDR_ABX  // 0xFF: ISC
};

// Decoder switch statement
static inline uint64_t _fam65xx_decode(fam65xx_t* c, uint64_t pins) {
    switch (c->IR) {

        // ==========================================
        // [0-255] OPCODE-SPECIFIC CYCLES
        // ==========================================

        case 0x00:  // BRK
            if(0==(c->brk_flags&(FAM65XX_BRK_IRQ|FAM65XX_BRK_NMI))){c->PC++;}BUS_WRITE(0x0100|c->S--,c->PC>>8);c->IR=294;
            break;

        case 0x01:  // ORA
        case 0x05:  // ORA
        case 0x09:  // ORA
        case 0x0D:  // ORA
        case 0x11:  // ORA
        case 0x15:  // ORA
        case 0x19:  // ORA
        case 0x1D:  // ORA
            BUS_READ(c->AD);c->A|=BUS_DATA();_NZ(c->A);_FETCH();
            break;

        case 0x02:  // JAM
        case 0x03:  // SLO
        case 0x06:  // ASL
        case 0x07:  // SLO
        case 0x0E:  // ASL
        case 0x0F:  // SLO
        case 0x12:  // JAM
        case 0x13:  // SLO
        case 0x16:  // ASL
        case 0x17:  // SLO
        case 0x1B:  // SLO
        case 0x1E:  // ASL
        case 0x1F:  // SLO
            BUS_READ(c->AD);c->AD=BUS_DATA();c->IR=295;
            break;

        case 0x04:  // NOP
        case 0x0B:  // ANC
        case 0x0C:  // NOP
        case 0x10:  // BPL
        case 0x14:  // NOP
        case 0x1A:  // NOP
        case 0x1C:  // NOP
        case 0x2B:  // ANC
        case 0x30:  // BMI
        case 0x34:  // NOP
        case 0x3A:  // NOP
        case 0x3C:  // NOP
        case 0x44:  // NOP
        case 0x4B:  // ASR
        case 0x50:  // BVC
        case 0x54:  // NOP
        case 0x5A:  // NOP
        case 0x5C:  // NOP
        case 0x64:  // NOP
        case 0x6B:  // ARR
        case 0x70:  // BVS
        case 0x74:  // NOP
        case 0x7A:  // NOP
        case 0x7C:  // NOP
        case 0x80:  // NOP
        case 0x82:  // NOP
        case 0x83:  // SAX
        case 0x87:  // SAX
        case 0x8B:  // XAA
        case 0x8F:  // SAX
        case 0x93:  // SHA
        case 0x97:  // SAX
        case 0x9B:  // SHS
        case 0x9F:  // SHY
        case 0xA3:  // LAX
        case 0xA7:  // LAX
        case 0xAB:  // LAX
        case 0xAF:  // LAX
        case 0xB3:  // LAX
        case 0xB7:  // LAX
        case 0xBB:  // LAS
        case 0xBF:  // LAX
        case 0xC2:  // NOP
        case 0xCB:  // SBX
        case 0xD4:  // NOP
        case 0xDA:  // NOP
        case 0xDC:  // NOP
        case 0xE2:  // NOP
        case 0xEB:  // SBC
        case 0xF4:  // NOP
        case 0xFA:  // NOP
        case 0xFC:  // NOP
            BUS_READ(c->PC);c->IR--;
            break;

        case 0x08:  // PHP
            BUS_WRITE(0x0100|c->S--,c->P|FAM65XX_XF);_FETCH();
            break;

        case 0x0A:  // ASL
            BUS_INTERNAL(c->PC);c->A=_fam65xx_asl(c,c->A);_FETCH();
            break;

        case 0x18:  // CLC
            BUS_INTERNAL(c->PC);c->P&=~FAM65XX_CF;_FETCH();
            break;

        case 0x20:  // JSR
            BUS_READ(c->PC++);c->AD=BUS_DATA();c->IR=296;
            break;

        case 0x21:  // AND
        case 0x25:  // AND
        case 0x29:  // AND
        case 0x2D:  // AND
        case 0x31:  // AND
        case 0x35:  // AND
        case 0x39:  // AND
        case 0x3D:  // AND
            BUS_READ(c->AD);c->A&=BUS_DATA();_NZ(c->A);_FETCH();
            break;

        case 0x22:  // JAM
        case 0x23:  // RLA
        case 0x26:  // ROL
        case 0x27:  // RLA
        case 0x2E:  // ROL
        case 0x2F:  // RLA
        case 0x32:  // JAM
        case 0x33:  // RLA
        case 0x36:  // ROL
        case 0x37:  // RLA
        case 0x3B:  // RLA
        case 0x3E:  // ROL
        case 0x3F:  // RLA
            BUS_READ(c->AD);c->AD=BUS_DATA();c->IR=297;
            break;

        case 0x24:  // BIT
        case 0x2C:  // BIT
            BUS_READ(c->AD);_fam65xx_bit(c,BUS_DATA());_FETCH();
            break;

        case 0x28:  // PLP
            BUS_INTERNAL(0x0100|c->S++);c->IR=298;
            break;

        case 0x2A:  // ROL
            BUS_INTERNAL(c->PC);c->A=_fam65xx_rol(c,c->A);_FETCH();
            break;

        case 0x38:  // SEC
            BUS_INTERNAL(c->PC);c->P|=FAM65XX_CF;_FETCH();
            break;

        case 0x40:  // RTI
            BUS_INTERNAL(0x0100|c->S++);c->IR=299;
            break;

        case 0x41:  // EOR
        case 0x45:  // EOR
        case 0x49:  // EOR
        case 0x4D:  // EOR
        case 0x51:  // EOR
        case 0x55:  // EOR
        case 0x59:  // EOR
        case 0x5D:  // EOR
            BUS_READ(c->AD);c->A^=BUS_DATA();_NZ(c->A);_FETCH();
            break;

        case 0x42:  // JAM
        case 0x43:  // SRE
        case 0x46:  // LSR
        case 0x47:  // SRE
        case 0x4E:  // LSR
        case 0x4F:  // SRE
        case 0x52:  // JAM
        case 0x53:  // SRE
        case 0x56:  // LSR
        case 0x57:  // SRE
        case 0x5B:  // SRE
        case 0x5E:  // LSR
        case 0x5F:  // SRE
            BUS_READ(c->AD);c->AD=BUS_DATA();c->IR=300;
            break;

        case 0x48:  // PHA
            BUS_WRITE(0x0100|c->S--,c->A);_FETCH();
            break;

        case 0x4A:  // LSR
            BUS_INTERNAL(c->PC);c->A=_fam65xx_lsr(c,c->A);_FETCH();
            break;

        case 0x4C:  // JMP
            BUS_READ(c->PC++);c->AD=BUS_DATA();c->IR=301;
            break;

        case 0x58:  // CLI
            BUS_INTERNAL(c->PC);c->P&=~FAM65XX_IF;_FETCH();
            break;

        case 0x60:  // RTS
            BUS_INTERNAL(0x0100|c->S++);c->IR=302;
            break;

        case 0x61:  // ADC
        case 0x65:  // ADC
        case 0x69:  // ADC
        case 0x6D:  // ADC
        case 0x71:  // ADC
        case 0x75:  // ADC
        case 0x79:  // ADC
        case 0x7D:  // ADC
            BUS_READ(c->AD);_fam65xx_adc(c,BUS_DATA());_FETCH();
            break;

        case 0x62:  // JAM
        case 0x63:  // RRA
        case 0x66:  // ROR
        case 0x67:  // RRA
        case 0x6E:  // ROR
        case 0x6F:  // RRA
        case 0x72:  // JAM
        case 0x73:  // RRA
        case 0x76:  // ROR
        case 0x77:  // RRA
        case 0x7B:  // RRA
        case 0x7E:  // ROR
        case 0x7F:  // RRA
            BUS_READ(c->AD);c->AD=BUS_DATA();c->IR=303;
            break;

        case 0x68:  // PLA
            BUS_INTERNAL(0x0100|c->S++);c->IR=304;
            break;

        case 0x6A:  // ROR
            BUS_INTERNAL(c->PC);c->A=_fam65xx_ror(c,c->A);_FETCH();
            break;

        case 0x6C:  // JMP
            BUS_READ(c->PC++);c->AD=BUS_DATA();c->IR=305;
            break;

        case 0x78:  // SEI
            BUS_INTERNAL(c->PC);c->P|=FAM65XX_IF;_FETCH();
            break;

        case 0x81:  // STA
        case 0x85:  // STA
        case 0x89:  // NOP
        case 0x8D:  // STA
        case 0x91:  // STA
        case 0x95:  // STA
        case 0x99:  // STA
        case 0x9D:  // STA
            BUS_WRITE(c->AD,c->A);_FETCH();
            break;

        case 0x84:  // STY
        case 0x8C:  // STY
        case 0x94:  // STY
        case 0x9C:  // SHY
            BUS_WRITE(c->AD,c->Y);_FETCH();
            break;

        case 0x86:  // STX
        case 0x8E:  // STX
        case 0x92:  // JAM
        case 0x96:  // STX
        case 0x9E:  // SHX
            BUS_WRITE(c->AD,c->X);_FETCH();
            break;

        case 0x88:  // DEY
            BUS_INTERNAL(c->PC);c->Y--;_NZ(c->Y);_FETCH();
            break;

        case 0x8A:  // TXA
            BUS_INTERNAL(c->PC);c->A=c->X;_NZ(c->A);_FETCH();
            break;

        case 0x90:  // BCC
            BUS_READ(c->PC);c->AD=c->PC+(int8_t)BUS_DATA();if((c->P&FAM65XX_NF)==0){c->IR=306;}else{_FETCH();}
            break;

        case 0x98:  // TYA
            BUS_INTERNAL(c->PC);c->A=c->Y;_NZ(c->A);_FETCH();
            break;

        case 0x9A:  // TXS
            BUS_INTERNAL(c->PC);c->S=c->X;_FETCH();
            break;

        case 0xA0:  // LDY
        case 0xA4:  // LDY
        case 0xAC:  // LDY
        case 0xB4:  // LDY
        case 0xBC:  // LDY
            BUS_READ(c->AD);c->Y=BUS_DATA();_NZ(c->Y);_FETCH();
            break;

        case 0xA1:  // LDA
        case 0xA5:  // LDA
        case 0xA9:  // LDA
        case 0xAD:  // LDA
        case 0xB1:  // LDA
        case 0xB5:  // LDA
        case 0xB9:  // LDA
        case 0xBD:  // LDA
            BUS_READ(c->AD);c->A=BUS_DATA();_NZ(c->A);_FETCH();
            break;

        case 0xA2:  // LDX
        case 0xA6:  // LDX
        case 0xAE:  // LDX
        case 0xB2:  // JAM
        case 0xB6:  // LDX
        case 0xBE:  // LDX
            BUS_READ(c->AD);c->X=BUS_DATA();_NZ(c->X);_FETCH();
            break;

        case 0xA8:  // TAY
            BUS_INTERNAL(c->PC);c->Y=c->A;_NZ(c->Y);_FETCH();
            break;

        case 0xAA:  // TAX
            BUS_INTERNAL(c->PC);c->X=c->A;_NZ(c->X);_FETCH();
            break;

        case 0xB0:  // BCS
            BUS_READ(c->PC);c->AD=c->PC+(int8_t)BUS_DATA();if((c->P&FAM65XX_VF)==FAM65XX_VF){c->IR=306;}else{_FETCH();}
            break;

        case 0xB8:  // CLV
            BUS_INTERNAL(c->PC);c->P&=~FAM65XX_VF;_FETCH();
            break;

        case 0xBA:  // TSX
            BUS_INTERNAL(c->PC);c->X=c->S;_NZ(c->X);_FETCH();
            break;

        case 0xC0:  // CPY
        case 0xC4:  // CPY
        case 0xCC:  // CPY
            BUS_READ(c->AD);_fam65xx_cmp(c,c->Y,BUS_DATA());_FETCH();
            break;

        case 0xC1:  // CMP
        case 0xC5:  // CMP
        case 0xC9:  // CMP
        case 0xCD:  // CMP
        case 0xD1:  // CMP
        case 0xD5:  // CMP
        case 0xD9:  // CMP
        case 0xDD:  // CMP
            BUS_READ(c->AD);_fam65xx_cmp(c,c->A,BUS_DATA());_FETCH();
            break;

        case 0xC3:  // DCP
        case 0xC6:  // DEC
        case 0xC7:  // DCP
        case 0xCE:  // DEC
        case 0xCF:  // DCP
        case 0xD2:  // JAM
        case 0xD3:  // DCP
        case 0xD6:  // DEC
        case 0xD7:  // DCP
        case 0xDB:  // DCP
        case 0xDE:  // DEC
        case 0xDF:  // DCP
            BUS_READ(c->AD);c->AD=BUS_DATA();c->IR=307;
            break;

        case 0xC8:  // INY
            BUS_INTERNAL(c->PC);c->Y++;_NZ(c->Y);_FETCH();
            break;

        case 0xCA:  // DEX
            BUS_INTERNAL(c->PC);c->X--;_NZ(c->X);_FETCH();
            break;

        case 0xD0:  // BNE
            BUS_READ(c->PC);c->AD=c->PC+(int8_t)BUS_DATA();if((c->P&FAM65XX_CF)==0){c->IR=306;}else{_FETCH();}
            break;

        case 0xD8:  // CLD
            BUS_INTERNAL(c->PC);c->P&=~FAM65XX_DF;_FETCH();
            break;

        case 0xE0:  // CPX
        case 0xE4:  // CPX
        case 0xEC:  // CPX
            BUS_READ(c->AD);_fam65xx_cmp(c,c->X,BUS_DATA());_FETCH();
            break;

        case 0xE1:  // SBC
        case 0xE5:  // SBC
        case 0xE9:  // SBC
        case 0xED:  // SBC
        case 0xF1:  // SBC
        case 0xF5:  // SBC
        case 0xF9:  // SBC
        case 0xFD:  // SBC
            BUS_READ(c->AD);_fam65xx_sbc(c,BUS_DATA());_FETCH();
            break;

        case 0xE3:  // ISC
        case 0xE6:  // INC
        case 0xE7:  // ISC
        case 0xEE:  // INC
        case 0xEF:  // ISC
        case 0xF2:  // JAM
        case 0xF3:  // ISC
        case 0xF6:  // INC
        case 0xF7:  // ISC
        case 0xFB:  // ISC
        case 0xFE:  // INC
        case 0xFF:  // ISC
            BUS_READ(c->AD);c->AD=BUS_DATA();c->IR=308;
            break;

        case 0xE8:  // INX
            BUS_INTERNAL(c->PC);c->X++;_NZ(c->X);_FETCH();
            break;

        case 0xEA:  // NOP
            BUS_INTERNAL(c->PC);_FETCH();
            break;

        case 0xF0:  // BEQ
            BUS_READ(c->PC);c->AD=c->PC+(int8_t)BUS_DATA();if((c->P&FAM65XX_ZF)==FAM65XX_ZF){c->IR=306;}else{_FETCH();}
            break;

        case 0xF8:  // SED
            BUS_INTERNAL(c->PC);c->P|=FAM65XX_DF;_FETCH();
            break;

        // ==========================================
        // [256-293] SHARED ADDRESSING SEQUENCES
        // ==========================================

        case 256:  // IMM: immediate
            BUS_READ(c->PC++);
            c->AD = BUS_DATA();
            c->IR = c->opcode;
            break;

        case 258:  // ZP cycle 1
            BUS_READ(c->PC++);
            break;
        case 259:  // ZP cycle 2
            c->AD = BUS_DATA();
            c->IR = c->opcode;
            break;

        case 261:  // ZPX cycle 1
            BUS_READ(c->PC++);
            break;
        case 262:  // ZPX cycle 2
            c->AD = BUS_DATA();
            BUS_INTERNAL(c->AD);
            break;
        case 263:  // ZPX cycle 3
            c->AD = (c->AD + c->X) & 0xFF;
            c->IR = c->opcode;
            break;

        case 265:  // ZPY cycle 1
            BUS_READ(c->PC++);
            break;
        case 266:  // ZPY cycle 2
            c->AD = BUS_DATA();
            BUS_INTERNAL(c->AD);
            break;
        case 267:  // ZPY cycle 3
            c->AD = (c->AD + c->Y) & 0xFF;
            c->IR = c->opcode;
            break;

        case 269:  // ABS cycle 1
            BUS_READ(c->PC++);
            c->AD = BUS_DATA();
            break;
        case 270:  // ABS cycle 2
            BUS_READ(c->PC++);
            c->AD |= BUS_DATA() << 8;
            break;
        case 271:  // ABS cycle 3
            c->IR = c->opcode;
            break;

        case 273:  // ABX cycle 1
            BUS_READ(c->PC++);
            c->AD = BUS_DATA();
            break;
        case 274:  // ABX cycle 2
            BUS_READ(c->PC++);
            c->AD |= BUS_DATA() << 8;
            break;
        case 275:  // ABX cycle 3: check page crossing
            BUS_READ((c->AD & 0xFF00) | ((c->AD + c->X) & 0xFF));
            if (((c->AD >> 8) == ((c->AD + c->X) >> 8))) {
                c->AD += c->X;
                c->IR = c->opcode;
            }
            break;
        case 276:  // ABX cycle 4: page crossed
            c->AD += c->X;
            c->IR = c->opcode;
            break;

        case 278:  // ABY cycle 1
            BUS_READ(c->PC++);
            c->AD = BUS_DATA();
            break;
        case 279:  // ABY cycle 2
            BUS_READ(c->PC++);
            c->AD |= BUS_DATA() << 8;
            break;
        case 280:  // ABY cycle 3: check page crossing
            BUS_READ((c->AD & 0xFF00) | ((c->AD + c->Y) & 0xFF));
            if (((c->AD >> 8) == ((c->AD + c->Y) >> 8))) {
                c->AD += c->Y;
                c->IR = c->opcode;
            }
            break;
        case 281:  // ABY cycle 4: page crossed
            c->AD += c->Y;
            c->IR = c->opcode;
            break;

        case 283:  // IDX cycle 1
            BUS_READ(c->PC++);
            break;
        case 284:  // IDX cycle 2
            c->AD = BUS_DATA();
            BUS_INTERNAL(c->AD);
            break;
        case 285:  // IDX cycle 3
            c->AD = (c->AD + c->X) & 0xFF;
            BUS_READ(c->AD);
            break;
        case 286:  // IDX cycle 4
            BUS_READ((c->AD + 1) & 0xFF);
            c->AD = BUS_DATA();
            break;
        case 287:  // IDX cycle 5
            c->AD |= BUS_DATA() << 8;
            c->IR = c->opcode;
            break;

        case 289:  // IDY cycle 1
            BUS_READ(c->PC++);
            break;
        case 290:  // IDY cycle 2
            c->AD = BUS_DATA();
            BUS_READ(c->AD);
            break;
        case 291:  // IDY cycle 3
            BUS_READ((c->AD + 1) & 0xFF);
            c->AD = BUS_DATA();
            break;
        case 292:  // IDY cycle 4: check page crossing
            c->AD |= BUS_DATA() << 8;
            BUS_READ((c->AD & 0xFF00) | ((c->AD + c->Y) & 0xFF));
            if (((c->AD >> 8) == ((c->AD + c->Y) >> 8))) {
                c->AD += c->Y;
                c->IR = c->opcode;
            }
            break;
        case 293:  // IDY cycle 5: page crossed
            c->AD += c->Y;
            c->IR = c->opcode;
            break;

        // ==========================================
        // [294+] SHARED CONTINUATIONS
        // ==========================================

        // BRK continuation (starting at 294)
        case 294: BUS_WRITE(0x0100|c->S--,c->PC);BUS_WRITE(0x0100|c->S--,c->P|FAM65XX_XF);if(c->brk_flags&FAM65XX_BRK_RESET){c->AD=0xFFFC;}else{if(c->brk_flags&FAM65XX_BRK_NMI){c->AD=0xFFFA;}else{c->AD=0xFFFE;}};BUS_READ(c->AD++);c->P|=(FAM65XX_IF|FAM65XX_BF);c->brk_flags=0;BUS_READ(c->AD);c->AD=BUS_DATA();c->PC=(BUS_DATA()<<8)|c->AD;_FETCH();break;

        // ASL_RMW continuation (starting at 295)
        case 295: BUS_WRITE(c->AD,c->AD);c->AD=_fam65xx_asl(c,c->AD);BUS_WRITE(c->AD,c->AD);_FETCH();break;

        // JSR continuation (starting at 296)
        case 296: BUS_INTERNAL(0x0100|c->S);BUS_WRITE(0x0100|c->S--,c->PC>>8);BUS_WRITE(0x0100|c->S--,c->PC);BUS_READ(c->PC);c->PC=(BUS_DATA()<<8)|c->AD;_FETCH();break;

        // ROL_RMW continuation (starting at 297)
        case 297: BUS_WRITE(c->AD,c->AD);c->AD=_fam65xx_rol(c,c->AD);BUS_WRITE(c->AD,c->AD);_FETCH();break;

        // PLP continuation (starting at 298)
        case 298: BUS_READ(0x0100|c->S);c->P=(BUS_DATA()|FAM65XX_BF)&~FAM65XX_XF;_FETCH();break;

        // RTI continuation (starting at 299)
        case 299: BUS_READ(0x0100|c->S++);BUS_READ(0x0100|c->S++);c->P=(BUS_DATA()|FAM65XX_BF)&~FAM65XX_XF;BUS_READ(0x0100|c->S);c->AD=BUS_DATA();c->PC=(BUS_DATA()<<8)|c->AD;_FETCH();break;

        // LSR_RMW continuation (starting at 300)
        case 300: BUS_WRITE(c->AD,c->AD);c->AD=_fam65xx_lsr(c,c->AD);BUS_WRITE(c->AD,c->AD);_FETCH();break;

        // JMP_ABS continuation (starting at 301)
        case 301: BUS_READ(c->PC++);c->AD|=BUS_DATA()<<8;c->PC=c->AD;_FETCH();break;

        // RTS continuation (starting at 302)
        case 302: BUS_READ(0x0100|c->S++);BUS_READ(0x0100|c->S);c->AD=BUS_DATA();c->PC=(BUS_DATA()<<8)|c->AD;BUS_READ(c->PC++);_FETCH();break;

        // ROR_RMW continuation (starting at 303)
        case 303: BUS_WRITE(c->AD,c->AD);c->AD=_fam65xx_ror(c,c->AD);BUS_WRITE(c->AD,c->AD);_FETCH();break;

        // PLA continuation (starting at 304)
        case 304: BUS_READ(0x0100|c->S);c->A=BUS_DATA();_NZ(c->A);_FETCH();break;

        // JMP_IND continuation (starting at 305)
        case 305: BUS_READ(c->PC++);c->AD|=BUS_DATA()<<8;BUS_READ(c->AD);BUS_READ((c->AD&0xFF00)|((c->AD+1)&0xFF));c->AD=BUS_DATA();c->PC=(BUS_DATA()<<8)|c->AD;_FETCH();break;

        // BRANCH_TAKEN continuation (starting at 306)
        case 306: BUS_INTERNAL((c->PC&0xFF00)|(c->AD&0xFF));if((c->AD&0xFF00)==(c->PC&0xFF00)){c->PC=c->AD;c->irq_pip>>=1;c->nmi_pip>>=1;_FETCH()};c->PC=c->AD;_FETCH();break;

        // DEC_RMW continuation (starting at 307)
        case 307: BUS_WRITE(c->AD,c->AD);c->AD--;_NZ(c->AD);BUS_WRITE(c->AD,c->AD);_FETCH();break;

        // INC_RMW continuation (starting at 308)
        case 308: BUS_WRITE(c->AD,c->AD);c->AD++;_NZ(c->AD);BUS_WRITE(c->AD,c->AD);_FETCH();break;

    }
    c->IR++;
    return pins;
}
