/*
 * AUTO-GENERATED by fam65xx_gen.py
 * 65xx Family CPU Decoder
 * Optimized for maximum performance and 100% hardware accuracy
 * 
 * Layout:
 *   [0-255]   : Opcode-specific cycles
 *   [256-298] : Shared addressing mode sequences
 *   [299-363]  : Shared continuation sequences
 * Total cases: 364
 */

// Continuation sequence constants
#define C_BRK            299
#define C_SLO_RMW        303
#define C_ASL_RMW        306
#define C_BRANCH_TAKEN   309
#define C_JSR            311
#define C_RLA_RMW        316
#define C_ROL_RMW        319
#define C_PLP            322
#define C_RTI            324
#define C_SRE_RMW        328
#define C_LSR_RMW        331
#define C_JMP_ABS        334
#define C_RTS            336
#define C_RRA_RMW        340
#define C_ROR_RMW        343
#define C_PLA            346
#define C_JMP_IND        348
#define C_DCP_RMW        352
#define C_DEC_RMW        355
#define C_ISC_RMW        358
#define C_INC_RMW        361

// Addressing mode offset constants
// Offset 0 = direct opcode jump (no addressing mode)
// Other offsets use base correction of ADDR_SEQ_BASE (255)
#define ADDR_NON     0   // Direct opcode execution (no addressing mode)
#define ADDR_SEQ_BASE 255
#define ADDR_IMM     1   // Index 256
#define ADDR_ZER     2   // Index 257
#define ADDR_ZPX     4   // Index 259
#define ADDR_ZPY     7   // Index 262
#define ADDR_ABS     10  // Index 265
#define ADDR_ABX     13  // Index 268
#define ADDR_ABX_W   17  // Index 272
#define ADDR_ABY     21  // Index 276
#define ADDR_ABY_W   25  // Index 280
#define ADDR_IDX     29  // Index 284
#define ADDR_IDY     34  // Index 289
#define ADDR_IDY_W   39  // Index 294

// Lookup table: addressing mode start index for each opcode
static const uint8_t opcode_addr_start[256] = {
    ADDR_NON,  // 0x00: BRK [---] no addressing mode
    ADDR_IDX,  // 0x01: ORA [R] indexed indirect (zp,X)
    ADDR_NON,  // 0x02: JAM [RW] invalid instruction
    ADDR_IDX,  // 0x03: SLO [RW] indexed indirect (zp,X)
    ADDR_ZER,  // 0x04: NOP [R] zero page
    ADDR_ZER,  // 0x05: ORA [R] zero page
    ADDR_ZER,  // 0x06: ASL [RW] zero page
    ADDR_ZER,  // 0x07: SLO [RW] zero page
    ADDR_NON,  // 0x08: PHP [W] no addressing mode
    ADDR_IMM,  // 0x09: ORA [R] immediate
    ADDR_NON,  // 0x0A: ASL [---] no addressing mode
    ADDR_IMM,  // 0x0B: ANC [R] immediate
    ADDR_ABS,  // 0x0C: NOP [R] absolute
    ADDR_ABS,  // 0x0D: ORA [R] absolute
    ADDR_ABS,  // 0x0E: ASL [RW] absolute
    ADDR_ABS,  // 0x0F: SLO [RW] absolute
    ADDR_IMM,  // 0x10: BPL [R] immediate
    ADDR_IDY,  // 0x11: ORA [R] indirect indexed (zp),Y
    ADDR_NON,  // 0x12: JAM [RW] invalid instruction
    ADDR_IDY_W,  // 0x13: SLO [RW] indirect indexed (zp),Y (write - always takes extra cycle)
    ADDR_ZPX,  // 0x14: NOP [R] zero page,X
    ADDR_ZPX,  // 0x15: ORA [R] zero page,X
    ADDR_ZPX,  // 0x16: ASL [RW] zero page,X
    ADDR_ZPX,  // 0x17: SLO [RW] zero page,X
    ADDR_NON,  // 0x18: CLC [---] no addressing mode
    ADDR_ABY,  // 0x19: ORA [R] absolute,Y
    ADDR_NON,  // 0x1A: NOP [R] no addressing mode
    ADDR_ABY_W,  // 0x1B: SLO [RW] absolute,Y (write - always takes extra cycle)
    ADDR_ABX,  // 0x1C: NOP [R] absolute,X
    ADDR_ABX,  // 0x1D: ORA [R] absolute,X
    ADDR_ABX_W,  // 0x1E: ASL [RW] absolute,X (write - always takes extra cycle)
    ADDR_ABX_W,  // 0x1F: SLO [RW] absolute,X (write - always takes extra cycle)
    ADDR_NON,  // 0x20: JSR [R] special JSR
    ADDR_IDX,  // 0x21: AND [R] indexed indirect (zp,X)
    ADDR_NON,  // 0x22: JAM [RW] invalid instruction
    ADDR_IDX,  // 0x23: RLA [RW] indexed indirect (zp,X)
    ADDR_ZER,  // 0x24: BIT [R] zero page
    ADDR_ZER,  // 0x25: AND [R] zero page
    ADDR_ZER,  // 0x26: ROL [RW] zero page
    ADDR_ZER,  // 0x27: RLA [RW] zero page
    ADDR_NON,  // 0x28: PLP [---] no addressing mode
    ADDR_IMM,  // 0x29: AND [R] immediate
    ADDR_NON,  // 0x2A: ROL [---] no addressing mode
    ADDR_IMM,  // 0x2B: ANC [R] immediate
    ADDR_ABS,  // 0x2C: BIT [R] absolute
    ADDR_ABS,  // 0x2D: AND [R] absolute
    ADDR_ABS,  // 0x2E: ROL [RW] absolute
    ADDR_ABS,  // 0x2F: RLA [RW] absolute
    ADDR_IMM,  // 0x30: BMI [R] immediate
    ADDR_IDY,  // 0x31: AND [R] indirect indexed (zp),Y
    ADDR_NON,  // 0x32: JAM [RW] invalid instruction
    ADDR_IDY_W,  // 0x33: RLA [RW] indirect indexed (zp),Y (write - always takes extra cycle)
    ADDR_ZPX,  // 0x34: NOP [R] zero page,X
    ADDR_ZPX,  // 0x35: AND [R] zero page,X
    ADDR_ZPX,  // 0x36: ROL [RW] zero page,X
    ADDR_ZPX,  // 0x37: RLA [RW] zero page,X
    ADDR_NON,  // 0x38: SEC [---] no addressing mode
    ADDR_ABY,  // 0x39: AND [R] absolute,Y
    ADDR_NON,  // 0x3A: NOP [R] no addressing mode
    ADDR_ABY_W,  // 0x3B: RLA [RW] absolute,Y (write - always takes extra cycle)
    ADDR_ABX,  // 0x3C: NOP [R] absolute,X
    ADDR_ABX,  // 0x3D: AND [R] absolute,X
    ADDR_ABX_W,  // 0x3E: ROL [RW] absolute,X (write - always takes extra cycle)
    ADDR_ABX_W,  // 0x3F: RLA [RW] absolute,X (write - always takes extra cycle)
    ADDR_NON,  // 0x40: RTI [R] no addressing mode
    ADDR_IDX,  // 0x41: EOR [R] indexed indirect (zp,X)
    ADDR_NON,  // 0x42: JAM [RW] invalid instruction
    ADDR_IDX,  // 0x43: SRE [RW] indexed indirect (zp,X)
    ADDR_ZER,  // 0x44: NOP [R] zero page
    ADDR_ZER,  // 0x45: EOR [R] zero page
    ADDR_ZER,  // 0x46: LSR [RW] zero page
    ADDR_ZER,  // 0x47: SRE [RW] zero page
    ADDR_NON,  // 0x48: PHA [W] no addressing mode
    ADDR_IMM,  // 0x49: EOR [R] immediate
    ADDR_NON,  // 0x4A: LSR [---] no addressing mode
    ADDR_IMM,  // 0x4B: ASR [R] immediate
    ADDR_NON,  // 0x4C: JMP [R] special JMP
    ADDR_ABS,  // 0x4D: EOR [R] absolute
    ADDR_ABS,  // 0x4E: LSR [RW] absolute
    ADDR_ABS,  // 0x4F: SRE [RW] absolute
    ADDR_IMM,  // 0x50: BVC [R] immediate
    ADDR_IDY,  // 0x51: EOR [R] indirect indexed (zp),Y
    ADDR_NON,  // 0x52: JAM [RW] invalid instruction
    ADDR_IDY_W,  // 0x53: SRE [RW] indirect indexed (zp),Y (write - always takes extra cycle)
    ADDR_ZPX,  // 0x54: NOP [R] zero page,X
    ADDR_ZPX,  // 0x55: EOR [R] zero page,X
    ADDR_ZPX,  // 0x56: LSR [RW] zero page,X
    ADDR_ZPX,  // 0x57: SRE [RW] zero page,X
    ADDR_NON,  // 0x58: CLI [---] no addressing mode
    ADDR_ABY,  // 0x59: EOR [R] absolute,Y
    ADDR_NON,  // 0x5A: NOP [R] no addressing mode
    ADDR_ABY_W,  // 0x5B: SRE [RW] absolute,Y (write - always takes extra cycle)
    ADDR_ABX,  // 0x5C: NOP [R] absolute,X
    ADDR_ABX,  // 0x5D: EOR [R] absolute,X
    ADDR_ABX_W,  // 0x5E: LSR [RW] absolute,X (write - always takes extra cycle)
    ADDR_ABX_W,  // 0x5F: SRE [RW] absolute,X (write - always takes extra cycle)
    ADDR_NON,  // 0x60: RTS [R] no addressing mode
    ADDR_IDX,  // 0x61: ADC [R] indexed indirect (zp,X)
    ADDR_NON,  // 0x62: JAM [RW] invalid instruction
    ADDR_IDX,  // 0x63: RRA [RW] indexed indirect (zp,X)
    ADDR_ZER,  // 0x64: NOP [R] zero page
    ADDR_ZER,  // 0x65: ADC [R] zero page
    ADDR_ZER,  // 0x66: ROR [RW] zero page
    ADDR_ZER,  // 0x67: RRA [RW] zero page
    ADDR_NON,  // 0x68: PLA [---] no addressing mode
    ADDR_IMM,  // 0x69: ADC [R] immediate
    ADDR_NON,  // 0x6A: ROR [---] no addressing mode
    ADDR_IMM,  // 0x6B: ARR [R] immediate
    ADDR_NON,  // 0x6C: JMP [R] special JMP
    ADDR_ABS,  // 0x6D: ADC [R] absolute
    ADDR_ABS,  // 0x6E: ROR [RW] absolute
    ADDR_ABS,  // 0x6F: RRA [RW] absolute
    ADDR_IMM,  // 0x70: BVS [R] immediate
    ADDR_IDY,  // 0x71: ADC [R] indirect indexed (zp),Y
    ADDR_NON,  // 0x72: JAM [RW] invalid instruction
    ADDR_IDY_W,  // 0x73: RRA [RW] indirect indexed (zp),Y (write - always takes extra cycle)
    ADDR_ZPX,  // 0x74: NOP [R] zero page,X
    ADDR_ZPX,  // 0x75: ADC [R] zero page,X
    ADDR_ZPX,  // 0x76: ROR [RW] zero page,X
    ADDR_ZPX,  // 0x77: RRA [RW] zero page,X
    ADDR_NON,  // 0x78: SEI [---] no addressing mode
    ADDR_ABY,  // 0x79: ADC [R] absolute,Y
    ADDR_NON,  // 0x7A: NOP [R] no addressing mode
    ADDR_ABY_W,  // 0x7B: RRA [RW] absolute,Y (write - always takes extra cycle)
    ADDR_ABX,  // 0x7C: NOP [R] absolute,X
    ADDR_ABX,  // 0x7D: ADC [R] absolute,X
    ADDR_ABX_W,  // 0x7E: ROR [RW] absolute,X (write - always takes extra cycle)
    ADDR_ABX_W,  // 0x7F: RRA [RW] absolute,X (write - always takes extra cycle)
    ADDR_IMM,  // 0x80: NOP [R] immediate
    ADDR_IDX,  // 0x81: STA [W] indexed indirect (zp,X)
    ADDR_IMM,  // 0x82: NOP [R] immediate
    ADDR_IDX,  // 0x83: SAX [W] indexed indirect (zp,X)
    ADDR_ZER,  // 0x84: STY [W] zero page
    ADDR_ZER,  // 0x85: STA [W] zero page
    ADDR_ZER,  // 0x86: STX [W] zero page
    ADDR_ZER,  // 0x87: SAX [W] zero page
    ADDR_NON,  // 0x88: DEY [---] no addressing mode
    ADDR_IMM,  // 0x89: NOP [R] immediate
    ADDR_NON,  // 0x8A: TXA [---] no addressing mode
    ADDR_IMM,  // 0x8B: XAA [R] immediate
    ADDR_ABS,  // 0x8C: STY [W] absolute
    ADDR_ABS,  // 0x8D: STA [W] absolute
    ADDR_ABS,  // 0x8E: STX [W] absolute
    ADDR_ABS,  // 0x8F: SAX [W] absolute
    ADDR_IMM,  // 0x90: BCC [R] immediate
    ADDR_IDY_W,  // 0x91: STA [W] indirect indexed (zp),Y (write - always takes extra cycle)
    ADDR_NON,  // 0x92: JAM [RW] invalid instruction
    ADDR_IDY_W,  // 0x93: SHA [RW] indirect indexed (zp),Y (write - always takes extra cycle)
    ADDR_ZPX,  // 0x94: STY [W] zero page,X
    ADDR_ZPX,  // 0x95: STA [W] zero page,X
    ADDR_ZPY,  // 0x96: STX [W] zero page,Y
    ADDR_ZPY,  // 0x97: SAX [W] zero page,Y
    ADDR_NON,  // 0x98: TYA [---] no addressing mode
    ADDR_ABY_W,  // 0x99: STA [W] absolute,Y (write - always takes extra cycle)
    ADDR_NON,  // 0x9A: TXS [---] no addressing mode
    ADDR_ABY_W,  // 0x9B: SHS [W] absolute,Y (write - always takes extra cycle)
    ADDR_ABX_W,  // 0x9C: SHY [W] absolute,X (write - always takes extra cycle)
    ADDR_ABX_W,  // 0x9D: STA [W] absolute,X (write - always takes extra cycle)
    ADDR_ABY_W,  // 0x9E: SHX [W] absolute,Y (write - always takes extra cycle)
    ADDR_ABY_W,  // 0x9F: SHY [W] absolute,Y (write - always takes extra cycle)
    ADDR_IMM,  // 0xA0: LDY [R] immediate
    ADDR_IDX,  // 0xA1: LDA [R] indexed indirect (zp,X)
    ADDR_IMM,  // 0xA2: LDX [R] immediate
    ADDR_IDX,  // 0xA3: LAX [R] indexed indirect (zp,X)
    ADDR_ZER,  // 0xA4: LDY [R] zero page
    ADDR_ZER,  // 0xA5: LDA [R] zero page
    ADDR_ZER,  // 0xA6: LDX [R] zero page
    ADDR_ZER,  // 0xA7: LAX [R] zero page
    ADDR_NON,  // 0xA8: TAY [---] no addressing mode
    ADDR_IMM,  // 0xA9: LDA [R] immediate
    ADDR_NON,  // 0xAA: TAX [---] no addressing mode
    ADDR_IMM,  // 0xAB: LAX [R] immediate
    ADDR_ABS,  // 0xAC: LDY [R] absolute
    ADDR_ABS,  // 0xAD: LDA [R] absolute
    ADDR_ABS,  // 0xAE: LDX [R] absolute
    ADDR_ABS,  // 0xAF: LAX [R] absolute
    ADDR_IMM,  // 0xB0: BCS [R] immediate
    ADDR_IDY,  // 0xB1: LDA [R] indirect indexed (zp),Y
    ADDR_NON,  // 0xB2: JAM [RW] invalid instruction
    ADDR_IDY,  // 0xB3: LAX [R] indirect indexed (zp),Y
    ADDR_ZPX,  // 0xB4: LDY [R] zero page,X
    ADDR_ZPX,  // 0xB5: LDA [R] zero page,X
    ADDR_ZPY,  // 0xB6: LDX [R] zero page,Y
    ADDR_ZPY,  // 0xB7: LAX [R] zero page,Y
    ADDR_NON,  // 0xB8: CLV [---] no addressing mode
    ADDR_ABY,  // 0xB9: LDA [R] absolute,Y
    ADDR_NON,  // 0xBA: TSX [---] no addressing mode
    ADDR_ABY,  // 0xBB: LAS [R] absolute,Y
    ADDR_ABX,  // 0xBC: LDY [R] absolute,X
    ADDR_ABX,  // 0xBD: LDA [R] absolute,X
    ADDR_ABY,  // 0xBE: LDX [R] absolute,Y
    ADDR_ABY,  // 0xBF: LAX [R] absolute,Y
    ADDR_IMM,  // 0xC0: CPY [R] immediate
    ADDR_IDX,  // 0xC1: CMP [R] indexed indirect (zp,X)
    ADDR_IMM,  // 0xC2: NOP [R] immediate
    ADDR_IDX,  // 0xC3: DCP [RW] indexed indirect (zp,X)
    ADDR_ZER,  // 0xC4: CPY [R] zero page
    ADDR_ZER,  // 0xC5: CMP [R] zero page
    ADDR_ZER,  // 0xC6: DEC [RW] zero page
    ADDR_ZER,  // 0xC7: DCP [RW] zero page
    ADDR_NON,  // 0xC8: INY [---] no addressing mode
    ADDR_IMM,  // 0xC9: CMP [R] immediate
    ADDR_NON,  // 0xCA: DEX [---] no addressing mode
    ADDR_IMM,  // 0xCB: SBX [R] immediate
    ADDR_ABS,  // 0xCC: CPY [R] absolute
    ADDR_ABS,  // 0xCD: CMP [R] absolute
    ADDR_ABS,  // 0xCE: DEC [RW] absolute
    ADDR_ABS,  // 0xCF: DCP [RW] absolute
    ADDR_IMM,  // 0xD0: BNE [R] immediate
    ADDR_IDY,  // 0xD1: CMP [R] indirect indexed (zp),Y
    ADDR_NON,  // 0xD2: JAM [RW] invalid instruction
    ADDR_IDY_W,  // 0xD3: DCP [RW] indirect indexed (zp),Y (write - always takes extra cycle)
    ADDR_ZPX,  // 0xD4: NOP [R] zero page,X
    ADDR_ZPX,  // 0xD5: CMP [R] zero page,X
    ADDR_ZPX,  // 0xD6: DEC [RW] zero page,X
    ADDR_ZPX,  // 0xD7: DCP [RW] zero page,X
    ADDR_NON,  // 0xD8: CLD [---] no addressing mode
    ADDR_ABY,  // 0xD9: CMP [R] absolute,Y
    ADDR_NON,  // 0xDA: NOP [R] no addressing mode
    ADDR_ABY_W,  // 0xDB: DCP [RW] absolute,Y (write - always takes extra cycle)
    ADDR_ABX,  // 0xDC: NOP [R] absolute,X
    ADDR_ABX,  // 0xDD: CMP [R] absolute,X
    ADDR_ABX_W,  // 0xDE: DEC [RW] absolute,X (write - always takes extra cycle)
    ADDR_ABX_W,  // 0xDF: DCP [RW] absolute,X (write - always takes extra cycle)
    ADDR_IMM,  // 0xE0: CPX [R] immediate
    ADDR_IDX,  // 0xE1: SBC [R] indexed indirect (zp,X)
    ADDR_IMM,  // 0xE2: NOP [R] immediate
    ADDR_IDX,  // 0xE3: ISC [RW] indexed indirect (zp,X)
    ADDR_ZER,  // 0xE4: CPX [R] zero page
    ADDR_ZER,  // 0xE5: SBC [R] zero page
    ADDR_ZER,  // 0xE6: INC [RW] zero page
    ADDR_ZER,  // 0xE7: ISC [RW] zero page
    ADDR_NON,  // 0xE8: INX [---] no addressing mode
    ADDR_IMM,  // 0xE9: SBC [R] immediate
    ADDR_NON,  // 0xEA: NOP [---] no addressing mode
    ADDR_IMM,  // 0xEB: SBC [R] immediate
    ADDR_ABS,  // 0xEC: CPX [R] absolute
    ADDR_ABS,  // 0xED: SBC [R] absolute
    ADDR_ABS,  // 0xEE: INC [RW] absolute
    ADDR_ABS,  // 0xEF: ISC [RW] absolute
    ADDR_IMM,  // 0xF0: BEQ [R] immediate
    ADDR_IDY,  // 0xF1: SBC [R] indirect indexed (zp),Y
    ADDR_NON,  // 0xF2: JAM [RW] invalid instruction
    ADDR_IDY_W,  // 0xF3: ISC [RW] indirect indexed (zp),Y (write - always takes extra cycle)
    ADDR_ZPX,  // 0xF4: NOP [R] zero page,X
    ADDR_ZPX,  // 0xF5: SBC [R] zero page,X
    ADDR_ZPX,  // 0xF6: INC [RW] zero page,X
    ADDR_ZPX,  // 0xF7: ISC [RW] zero page,X
    ADDR_NON,  // 0xF8: SED [---] no addressing mode
    ADDR_ABY,  // 0xF9: SBC [R] absolute,Y
    ADDR_NON,  // 0xFA: NOP [R] no addressing mode
    ADDR_ABY_W,  // 0xFB: ISC [RW] absolute,Y (write - always takes extra cycle)
    ADDR_ABX,  // 0xFC: NOP [R] absolute,X
    ADDR_ABX,  // 0xFD: SBC [R] absolute,X
    ADDR_ABX_W,  // 0xFE: INC [RW] absolute,X (write - always takes extra cycle)
    ADDR_ABX_W   // 0xFF: ISC [RW] absolute,X (write - always takes extra cycle)
};

// Decoder switch statement
static inline uint64_t _fam65xx_decode(fam65xx_t* c, uint64_t pins) {
    switch (c->IR) {

        // ==========================================
        // [0-255] OPCODE-SPECIFIC CYCLES
        // ==========================================

        case 0x00:  // BRK [---] --- cycle 1
            if (0 == (c->brk_flags & (FAM65XX_BRK_IRQ | FAM65XX_BRK_NMI))) {
            	c->PC++;
            }
            BUS_WRITE(0x0100 | c->S--, c->PC >> 8);
            c->IR = C_BRK;
            break;

        case 0x01:  // ORA [R] IDX cycle 6
        case 0x05:  // ORA [R] ZP cycle 3
        case 0x09:  // ORA [R] IMM cycle 2
        case 0x0D:  // ORA [R] ABS cycle 4
        case 0x11:  // ORA [R] IDY cycle 6
        case 0x15:  // ORA [R] ZPX cycle 4
        case 0x19:  // ORA [R] ABY cycle 5
        case 0x1D:  // ORA [R] ABX cycle 5
            BUS_READ(c->AD);
            c->A |= BUS_DATA();
            _NZ(c->A);
            _FETCH();
            break;

        case 0x02:  // JAM [RW] --- cycle 1
        case 0x12:  // JAM [RW] --- cycle 1
        case 0x22:  // JAM [RW] --- cycle 1
        case 0x32:  // JAM [RW] --- cycle 1
        case 0x42:  // JAM [RW] --- cycle 1
        case 0x52:  // JAM [RW] --- cycle 1
        case 0x62:  // JAM [RW] --- cycle 1
        case 0x72:  // JAM [RW] --- cycle 1
        case 0x92:  // JAM [RW] --- cycle 1
        case 0xB2:  // JAM [RW] --- cycle 1
        case 0xD2:  // JAM [RW] --- cycle 1
        case 0xF2:  // JAM [RW] --- cycle 1
            BUS_READ(c->PC);
            c->IR--;
            break;

        case 0x03:  // SLO [RW] IDX cycle 6
        case 0x07:  // SLO [RW] ZP cycle 3
        case 0x0F:  // SLO [RW] ABS cycle 4
        case 0x13:  // SLO [RW] IDY cycle 6
        case 0x17:  // SLO [RW] ZPX cycle 4
        case 0x1B:  // SLO [RW] ABY cycle 5
        case 0x1F:  // SLO [RW] ABX cycle 5
            BUS_READ(c->AD);
            c->AD = BUS_DATA();
            c->IR = C_SLO_RMW;
            break;

        case 0x04:  // NOP [R] ZP cycle 3
        case 0x0C:  // NOP [R] ABS cycle 4
        case 0x14:  // NOP [R] ZPX cycle 4
        case 0x1A:  // NOP [R] --- cycle 1
        case 0x1C:  // NOP [R] ABX cycle 5
        case 0x34:  // NOP [R] ZPX cycle 4
        case 0x3A:  // NOP [R] --- cycle 1
        case 0x3C:  // NOP [R] ABX cycle 5
        case 0x44:  // NOP [R] ZP cycle 3
        case 0x54:  // NOP [R] ZPX cycle 4
        case 0x5A:  // NOP [R] --- cycle 1
        case 0x5C:  // NOP [R] ABX cycle 5
        case 0x64:  // NOP [R] ZP cycle 3
        case 0x74:  // NOP [R] ZPX cycle 4
        case 0x7A:  // NOP [R] --- cycle 1
        case 0x7C:  // NOP [R] ABX cycle 5
        case 0x80:  // NOP [R] IMM cycle 2
        case 0x82:  // NOP [R] IMM cycle 2
        case 0x89:  // NOP [R] IMM cycle 2
        case 0xC2:  // NOP [R] IMM cycle 2
        case 0xD4:  // NOP [R] ZPX cycle 4
        case 0xDA:  // NOP [R] --- cycle 1
        case 0xDC:  // NOP [R] ABX cycle 5
        case 0xE2:  // NOP [R] IMM cycle 2
        case 0xF4:  // NOP [R] ZPX cycle 4
        case 0xFA:  // NOP [R] --- cycle 1
        case 0xFC:  // NOP [R] ABX cycle 5
            BUS_READ(c->AD);
            _FETCH();
            break;

        case 0x06:  // ASL [RW] ZP cycle 3
        case 0x0E:  // ASL [RW] ABS cycle 4
        case 0x16:  // ASL [RW] ZPX cycle 4
        case 0x1E:  // ASL [RW] ABX cycle 5
            BUS_READ(c->AD);
            c->AD = BUS_DATA();
            c->IR = C_ASL_RMW;
            break;

        case 0x08:  // PHP [W] --- cycle 1
            BUS_WRITE(0x0100 | c->S--, c->P | FAM65XX_XF);
            _FETCH();
            break;

        case 0x0A:  // ASL [---] --- cycle 1
            BUS_INTERNAL(c->PC);
            c->A = _fam65xx_asl(c, c->A);
            _FETCH();
            break;

        case 0x0B:  // ANC [R] IMM cycle 2
        case 0x2B:  // ANC [R] IMM cycle 2
            BUS_READ(c->AD);
            c->A &= BUS_DATA();
            _NZ(c->A);
            c->P = (c->P & ~FAM65XX_CF) | ((c->A & 0x80) ? FAM65XX_CF : 0);
            _FETCH();
            break;

        case 0x10:  // BPL [R] IMM cycle 2
        case 0x90:  // BCC [R] IMM cycle 2
            BUS_READ(c->PC);
            c->AD = c->PC + (int8_t)BUS_DATA();
            if ((c->P & FAM65XX_NF) == 0) {
            	c->IR = C_BRANCH_TAKEN;
            } else {
            	_FETCH();
            }
            break;

        case 0x18:  // CLC [---] --- cycle 1
            BUS_INTERNAL(c->PC);
            c->P &= ~FAM65XX_CF;
            _FETCH();
            break;

        case 0x20:  // JSR [R] --- cycle 1
            BUS_READ(c->PC++);
            c->AD = BUS_DATA();
            c->IR = C_JSR;
            break;

        case 0x21:  // AND [R] IDX cycle 6
        case 0x25:  // AND [R] ZP cycle 3
        case 0x29:  // AND [R] IMM cycle 2
        case 0x2D:  // AND [R] ABS cycle 4
        case 0x31:  // AND [R] IDY cycle 6
        case 0x35:  // AND [R] ZPX cycle 4
        case 0x39:  // AND [R] ABY cycle 5
        case 0x3D:  // AND [R] ABX cycle 5
            BUS_READ(c->AD);
            c->A &= BUS_DATA();
            _NZ(c->A);
            _FETCH();
            break;

        case 0x23:  // RLA [RW] IDX cycle 6
        case 0x27:  // RLA [RW] ZP cycle 3
        case 0x2F:  // RLA [RW] ABS cycle 4
        case 0x33:  // RLA [RW] IDY cycle 6
        case 0x37:  // RLA [RW] ZPX cycle 4
        case 0x3B:  // RLA [RW] ABY cycle 5
        case 0x3F:  // RLA [RW] ABX cycle 5
            BUS_READ(c->AD);
            c->AD = BUS_DATA();
            c->IR = C_RLA_RMW;
            break;

        case 0x24:  // BIT [R] ZP cycle 3
        case 0x2C:  // BIT [R] ABS cycle 4
            BUS_READ(c->AD);
            _fam65xx_bit(c, BUS_DATA());
            _FETCH();
            break;

        case 0x26:  // ROL [RW] ZP cycle 3
        case 0x2E:  // ROL [RW] ABS cycle 4
        case 0x36:  // ROL [RW] ZPX cycle 4
        case 0x3E:  // ROL [RW] ABX cycle 5
            BUS_READ(c->AD);
            c->AD = BUS_DATA();
            c->IR = C_ROL_RMW;
            break;

        case 0x28:  // PLP [---] --- cycle 1
            BUS_INTERNAL(0x0100 | c->S++);
            c->IR = C_PLP;
            break;

        case 0x2A:  // ROL [---] --- cycle 1
            BUS_INTERNAL(c->PC);
            c->A = _fam65xx_rol(c, c->A);
            _FETCH();
            break;

        case 0x30:  // BMI [R] IMM cycle 2
        case 0xB0:  // BCS [R] IMM cycle 2
            BUS_READ(c->PC);
            c->AD = c->PC + (int8_t)BUS_DATA();
            if ((c->P & FAM65XX_VF) == FAM65XX_VF) {
            	c->IR = C_BRANCH_TAKEN;
            } else {
            	_FETCH();
            }
            break;

        case 0x38:  // SEC [---] --- cycle 1
            BUS_INTERNAL(c->PC);
            c->P |= FAM65XX_CF;
            _FETCH();
            break;

        case 0x40:  // RTI [R] --- cycle 1
            BUS_INTERNAL(0x0100 | c->S++);
            c->IR = C_RTI;
            break;

        case 0x41:  // EOR [R] IDX cycle 6
        case 0x45:  // EOR [R] ZP cycle 3
        case 0x49:  // EOR [R] IMM cycle 2
        case 0x4D:  // EOR [R] ABS cycle 4
        case 0x51:  // EOR [R] IDY cycle 6
        case 0x55:  // EOR [R] ZPX cycle 4
        case 0x59:  // EOR [R] ABY cycle 5
        case 0x5D:  // EOR [R] ABX cycle 5
            BUS_READ(c->AD);
            c->A ^= BUS_DATA();
            _NZ(c->A);
            _FETCH();
            break;

        case 0x43:  // SRE [RW] IDX cycle 6
        case 0x47:  // SRE [RW] ZP cycle 3
        case 0x4F:  // SRE [RW] ABS cycle 4
        case 0x53:  // SRE [RW] IDY cycle 6
        case 0x57:  // SRE [RW] ZPX cycle 4
        case 0x5B:  // SRE [RW] ABY cycle 5
        case 0x5F:  // SRE [RW] ABX cycle 5
            BUS_READ(c->AD);
            c->AD = BUS_DATA();
            c->IR = C_SRE_RMW;
            break;

        case 0x46:  // LSR [RW] ZP cycle 3
        case 0x4E:  // LSR [RW] ABS cycle 4
        case 0x56:  // LSR [RW] ZPX cycle 4
        case 0x5E:  // LSR [RW] ABX cycle 5
            BUS_READ(c->AD);
            c->AD = BUS_DATA();
            c->IR = C_LSR_RMW;
            break;

        case 0x48:  // PHA [W] --- cycle 1
            BUS_WRITE(0x0100 | c->S--, c->A);
            _FETCH();
            break;

        case 0x4A:  // LSR [---] --- cycle 1
            BUS_INTERNAL(c->PC);
            c->A = _fam65xx_lsr(c, c->A);
            _FETCH();
            break;

        case 0x4B:  // ASR [R] IMM cycle 2
            BUS_READ(c->AD);
            c->A &= BUS_DATA();
            c->P = (c->P & ~FAM65XX_CF) | (c->A & 1);
            c->A>>=1;
            _NZ(c->A);
            _FETCH();
            break;

        case 0x4C:  // JMP [R] --- cycle 1
            BUS_READ(c->PC++);
            c->AD = BUS_DATA();
            c->IR = C_JMP_ABS;
            break;

        case 0x50:  // BVC [R] IMM cycle 2
        case 0xD0:  // BNE [R] IMM cycle 2
            BUS_READ(c->PC);
            c->AD = c->PC + (int8_t)BUS_DATA();
            if ((c->P & FAM65XX_CF) == 0) {
            	c->IR = C_BRANCH_TAKEN;
            } else {
            	_FETCH();
            }
            break;

        case 0x58:  // CLI [---] --- cycle 1
            BUS_INTERNAL(c->PC);
            c->P &= ~FAM65XX_IF;
            _FETCH();
            break;

        case 0x60:  // RTS [R] --- cycle 1
            BUS_INTERNAL(0x0100 | c->S++);
            c->IR = C_RTS;
            break;

        case 0x61:  // ADC [R] IDX cycle 6
        case 0x65:  // ADC [R] ZP cycle 3
        case 0x69:  // ADC [R] IMM cycle 2
        case 0x6D:  // ADC [R] ABS cycle 4
        case 0x71:  // ADC [R] IDY cycle 6
        case 0x75:  // ADC [R] ZPX cycle 4
        case 0x79:  // ADC [R] ABY cycle 5
        case 0x7D:  // ADC [R] ABX cycle 5
            BUS_READ(c->AD);
            _fam65xx_adc(c, BUS_DATA());
            _FETCH();
            break;

        case 0x63:  // RRA [RW] IDX cycle 6
        case 0x67:  // RRA [RW] ZP cycle 3
        case 0x6F:  // RRA [RW] ABS cycle 4
        case 0x73:  // RRA [RW] IDY cycle 6
        case 0x77:  // RRA [RW] ZPX cycle 4
        case 0x7B:  // RRA [RW] ABY cycle 5
        case 0x7F:  // RRA [RW] ABX cycle 5
            BUS_READ(c->AD);
            c->AD = BUS_DATA();
            c->IR = C_RRA_RMW;
            break;

        case 0x66:  // ROR [RW] ZP cycle 3
        case 0x6E:  // ROR [RW] ABS cycle 4
        case 0x76:  // ROR [RW] ZPX cycle 4
        case 0x7E:  // ROR [RW] ABX cycle 5
            BUS_READ(c->AD);
            c->AD = BUS_DATA();
            c->IR = C_ROR_RMW;
            break;

        case 0x68:  // PLA [---] --- cycle 1
            BUS_INTERNAL(0x0100 | c->S++);
            c->IR = C_PLA;
            break;

        case 0x6A:  // ROR [---] --- cycle 1
            BUS_INTERNAL(c->PC);
            c->A = _fam65xx_ror(c, c->A);
            _FETCH();
            break;

        case 0x6B:  // ARR [R] IMM cycle 2
            BUS_READ(c->AD);
            c->A = (c->A & BUS_DATA()) >> 1 | (c->P & FAM65XX_CF ? 0x80 : 0);
            _NZ(c->A);
            c->P = (c->P & ~(FAM65XX_CF | FAM65XX_VF)) | ((c->A & 0x40) ? FAM65XX_CF : 0) | ((c->A & 0x20) ^ (c->A & 0x40) ? FAM65XX_VF : 0);
            _FETCH();
            break;

        case 0x6C:  // JMP [R] --- cycle 1
            BUS_READ(c->PC++);
            c->AD = BUS_DATA();
            c->IR = C_JMP_IND;
            break;

        case 0x70:  // BVS [R] IMM cycle 2
        case 0xF0:  // BEQ [R] IMM cycle 2
            BUS_READ(c->PC);
            c->AD = c->PC + (int8_t)BUS_DATA();
            if ((c->P & FAM65XX_ZF) == FAM65XX_ZF) {
            	c->IR = C_BRANCH_TAKEN;
            } else {
            	_FETCH();
            }
            break;

        case 0x78:  // SEI [---] --- cycle 1
            BUS_INTERNAL(c->PC);
            c->P |= FAM65XX_IF;
            _FETCH();
            break;

        case 0x81:  // STA [W] IDX cycle 6
        case 0x85:  // STA [W] ZP cycle 3
        case 0x8D:  // STA [W] ABS cycle 4
        case 0x91:  // STA [W] IDY cycle 6
        case 0x95:  // STA [W] ZPX cycle 4
        case 0x99:  // STA [W] ABY cycle 5
        case 0x9D:  // STA [W] ABX cycle 5
            BUS_WRITE(c->AD, c->A);
            _FETCH();
            break;

        case 0x83:  // SAX [W] IDX cycle 6
        case 0x87:  // SAX [W] ZP cycle 3
        case 0x8F:  // SAX [W] ABS cycle 4
        case 0x97:  // SAX [W] ZPY cycle 4
            BUS_WRITE(c->AD, c->A & c->X);
            _FETCH();
            break;

        case 0x84:  // STY [W] ZP cycle 3
        case 0x8C:  // STY [W] ABS cycle 4
        case 0x94:  // STY [W] ZPX cycle 4
            BUS_WRITE(c->AD, c->Y);
            _FETCH();
            break;

        case 0x86:  // STX [W] ZP cycle 3
        case 0x8E:  // STX [W] ABS cycle 4
        case 0x96:  // STX [W] ZPY cycle 4
            BUS_WRITE(c->AD, c->X);
            _FETCH();
            break;

        case 0x88:  // DEY [---] --- cycle 1
            BUS_INTERNAL(c->PC);
            c->Y--;
            _NZ(c->Y);
            _FETCH();
            break;

        case 0x8A:  // TXA [---] --- cycle 1
            BUS_INTERNAL(c->PC);
            c->A = c->X;
            _NZ(c->A);
            _FETCH();
            break;

        case 0x8B:  // XAA [R] IMM cycle 2
            BUS_READ(c->AD);
            c->A = (c->A | 0xEE) & c->X & BUS_DATA();
            _NZ(c->A);
            _FETCH();
            break;

        case 0x93:  // SHA [RW] IDY cycle 6
            BUS_WRITE(c->AD, c->A & c->X & ((c->AD >> 8) + 1));
            _FETCH();
            break;

        case 0x98:  // TYA [---] --- cycle 1
            BUS_INTERNAL(c->PC);
            c->A = c->Y;
            _NZ(c->A);
            _FETCH();
            break;

        case 0x9A:  // TXS [---] --- cycle 1
            BUS_INTERNAL(c->PC);
            c->S = c->X;
            _FETCH();
            break;

        case 0x9B:  // SHS [W] ABY cycle 5
            c->S = c->A & c->X;
            BUS_WRITE(c->AD, c->S & ((c->AD >> 8) + 1));
            _FETCH();
            break;

        case 0x9C:  // SHY [W] ABX cycle 5
        case 0x9F:  // SHY [W] ABY cycle 5
            BUS_WRITE(c->AD, c->Y & ((c->AD >> 8) + 1));
            _FETCH();
            break;

        case 0x9E:  // SHX [W] ABY cycle 5
            BUS_WRITE(c->AD, c->X & ((c->AD >> 8) + 1));
            _FETCH();
            break;

        case 0xA0:  // LDY [R] IMM cycle 2
        case 0xA4:  // LDY [R] ZP cycle 3
        case 0xAC:  // LDY [R] ABS cycle 4
        case 0xB4:  // LDY [R] ZPX cycle 4
        case 0xBC:  // LDY [R] ABX cycle 5
            BUS_READ(c->AD);
            c->Y = BUS_DATA();
            _NZ(c->Y);
            _FETCH();
            break;

        case 0xA1:  // LDA [R] IDX cycle 6
        case 0xA5:  // LDA [R] ZP cycle 3
        case 0xA9:  // LDA [R] IMM cycle 2
        case 0xAD:  // LDA [R] ABS cycle 4
        case 0xB1:  // LDA [R] IDY cycle 6
        case 0xB5:  // LDA [R] ZPX cycle 4
        case 0xB9:  // LDA [R] ABY cycle 5
        case 0xBD:  // LDA [R] ABX cycle 5
            BUS_READ(c->AD);
            c->A = BUS_DATA();
            _NZ(c->A);
            _FETCH();
            break;

        case 0xA2:  // LDX [R] IMM cycle 2
        case 0xA6:  // LDX [R] ZP cycle 3
        case 0xAE:  // LDX [R] ABS cycle 4
        case 0xB6:  // LDX [R] ZPY cycle 4
        case 0xBE:  // LDX [R] ABY cycle 5
            BUS_READ(c->AD);
            c->X = BUS_DATA();
            _NZ(c->X);
            _FETCH();
            break;

        case 0xA3:  // LAX [R] IDX cycle 6
        case 0xA7:  // LAX [R] ZP cycle 3
        case 0xAB:  // LAX [R] IMM cycle 2
        case 0xAF:  // LAX [R] ABS cycle 4
        case 0xB3:  // LAX [R] IDY cycle 6
        case 0xB7:  // LAX [R] ZPY cycle 4
        case 0xBF:  // LAX [R] ABY cycle 5
            BUS_READ(c->AD);
            c->A = c->X = BUS_DATA();
            _NZ(c->A);
            _FETCH();
            break;

        case 0xA8:  // TAY [---] --- cycle 1
            BUS_INTERNAL(c->PC);
            c->Y = c->A;
            _NZ(c->Y);
            _FETCH();
            break;

        case 0xAA:  // TAX [---] --- cycle 1
            BUS_INTERNAL(c->PC);
            c->X = c->A;
            _NZ(c->X);
            _FETCH();
            break;

        case 0xB8:  // CLV [---] --- cycle 1
            BUS_INTERNAL(c->PC);
            c->P &= ~FAM65XX_VF;
            _FETCH();
            break;

        case 0xBA:  // TSX [---] --- cycle 1
            BUS_INTERNAL(c->PC);
            c->X = c->S;
            _NZ(c->X);
            _FETCH();
            break;

        case 0xBB:  // LAS [R] ABY cycle 5
            BUS_READ(c->AD);
            c->A = c->X = c->S = c->S & BUS_DATA();
            _NZ(c->A);
            _FETCH();
            break;

        case 0xC0:  // CPY [R] IMM cycle 2
        case 0xC4:  // CPY [R] ZP cycle 3
        case 0xCC:  // CPY [R] ABS cycle 4
            BUS_READ(c->AD);
            _fam65xx_cmp(c, c->Y, BUS_DATA());
            _FETCH();
            break;

        case 0xC1:  // CMP [R] IDX cycle 6
        case 0xC5:  // CMP [R] ZP cycle 3
        case 0xC9:  // CMP [R] IMM cycle 2
        case 0xCD:  // CMP [R] ABS cycle 4
        case 0xD1:  // CMP [R] IDY cycle 6
        case 0xD5:  // CMP [R] ZPX cycle 4
        case 0xD9:  // CMP [R] ABY cycle 5
        case 0xDD:  // CMP [R] ABX cycle 5
            BUS_READ(c->AD);
            _fam65xx_cmp(c, c->A, BUS_DATA());
            _FETCH();
            break;

        case 0xC3:  // DCP [RW] IDX cycle 6
        case 0xC7:  // DCP [RW] ZP cycle 3
        case 0xCF:  // DCP [RW] ABS cycle 4
        case 0xD3:  // DCP [RW] IDY cycle 6
        case 0xD7:  // DCP [RW] ZPX cycle 4
        case 0xDB:  // DCP [RW] ABY cycle 5
        case 0xDF:  // DCP [RW] ABX cycle 5
            BUS_READ(c->AD);
            c->AD = BUS_DATA();
            c->IR = C_DCP_RMW;
            break;

        case 0xC6:  // DEC [RW] ZP cycle 3
        case 0xCE:  // DEC [RW] ABS cycle 4
        case 0xD6:  // DEC [RW] ZPX cycle 4
        case 0xDE:  // DEC [RW] ABX cycle 5
            BUS_READ(c->AD);
            c->AD = BUS_DATA();
            c->IR = C_DEC_RMW;
            break;

        case 0xC8:  // INY [---] --- cycle 1
            BUS_INTERNAL(c->PC);
            c->Y++;
            _NZ(c->Y);
            _FETCH();
            break;

        case 0xCA:  // DEX [---] --- cycle 1
            BUS_INTERNAL(c->PC);
            c->X--;
            _NZ(c->X);
            _FETCH();
            break;

        case 0xCB:  // SBX [R] IMM cycle 2
            BUS_READ(c->AD);
            {
            	uint16_t t = (c->A & c->X) - BUS_DATA();
            	c->X = t;
            _NZ(c->X);
            c->P = (c->P & ~FAM65XX_CF) | ((t & 0x100) ? 0 : FAM65XX_CF);
            }
            _FETCH();
            break;

        case 0xD8:  // CLD [---] --- cycle 1
            BUS_INTERNAL(c->PC);
            c->P &= ~FAM65XX_DF;
            _FETCH();
            break;

        case 0xE0:  // CPX [R] IMM cycle 2
        case 0xE4:  // CPX [R] ZP cycle 3
        case 0xEC:  // CPX [R] ABS cycle 4
            BUS_READ(c->AD);
            _fam65xx_cmp(c, c->X, BUS_DATA());
            _FETCH();
            break;

        case 0xE1:  // SBC [R] IDX cycle 6
        case 0xE5:  // SBC [R] ZP cycle 3
        case 0xE9:  // SBC [R] IMM cycle 2
        case 0xEB:  // SBC [R] IMM cycle 2
        case 0xED:  // SBC [R] ABS cycle 4
        case 0xF1:  // SBC [R] IDY cycle 6
        case 0xF5:  // SBC [R] ZPX cycle 4
        case 0xF9:  // SBC [R] ABY cycle 5
        case 0xFD:  // SBC [R] ABX cycle 5
            BUS_READ(c->AD);
            _fam65xx_sbc(c, BUS_DATA());
            _FETCH();
            break;

        case 0xE3:  // ISC [RW] IDX cycle 6
        case 0xE7:  // ISC [RW] ZP cycle 3
        case 0xEF:  // ISC [RW] ABS cycle 4
        case 0xF3:  // ISC [RW] IDY cycle 6
        case 0xF7:  // ISC [RW] ZPX cycle 4
        case 0xFB:  // ISC [RW] ABY cycle 5
        case 0xFF:  // ISC [RW] ABX cycle 5
            BUS_READ(c->AD);
            c->AD = BUS_DATA();
            c->IR = C_ISC_RMW;
            break;

        case 0xE6:  // INC [RW] ZP cycle 3
        case 0xEE:  // INC [RW] ABS cycle 4
        case 0xF6:  // INC [RW] ZPX cycle 4
        case 0xFE:  // INC [RW] ABX cycle 5
            BUS_READ(c->AD);
            c->AD = BUS_DATA();
            c->IR = C_INC_RMW;
            break;

        case 0xE8:  // INX [---] --- cycle 1
            BUS_INTERNAL(c->PC);
            c->X++;
            _NZ(c->X);
            _FETCH();
            break;

        case 0xEA:  // NOP [---] --- cycle 1
            BUS_INTERNAL(c->PC);
            _FETCH();
            break;

        case 0xF8:  // SED [---] --- cycle 1
            BUS_INTERNAL(c->PC);
            c->P |= FAM65XX_DF;
            _FETCH();
            break;

        // ==========================================
        // [256-298] SHARED ADDRESSING SEQUENCES
        // ==========================================

        // IMM: immediate
        case ADDR_SEQ_BASE + ADDR_IMM + 0:  // IMM cycle 1
            BUS_READ(c->PC++);
            c->AD = BUS_DATA();
            c->IR = c->opcode;
            break;

        // ZP: zero page
        case ADDR_SEQ_BASE + ADDR_ZER + 0:  // ZP cycle 1
            BUS_READ(c->PC++);
            break;
        case ADDR_SEQ_BASE + ADDR_ZER + 1:  // ZP cycle 2
            c->AD = BUS_DATA();
            c->IR = c->opcode;
            break;

        // ZPX: zero page,X
        case ADDR_SEQ_BASE + ADDR_ZPX + 0:  // ZPX cycle 1
            BUS_READ(c->PC++);
            break;
        case ADDR_SEQ_BASE + ADDR_ZPX + 1:  // ZPX cycle 2
            c->AD = BUS_DATA();
            BUS_INTERNAL(c->AD);
            break;
        case ADDR_SEQ_BASE + ADDR_ZPX + 2:  // ZPX cycle 3
            c->AD = (c->AD + c->X) & 0xFF;
            c->IR = c->opcode;
            break;

        // ZPY: zero page,Y
        case ADDR_SEQ_BASE + ADDR_ZPY + 0:  // ZPY cycle 1
            BUS_READ(c->PC++);
            break;
        case ADDR_SEQ_BASE + ADDR_ZPY + 1:  // ZPY cycle 2
            c->AD = BUS_DATA();
            BUS_INTERNAL(c->AD);
            break;
        case ADDR_SEQ_BASE + ADDR_ZPY + 2:  // ZPY cycle 3
            c->AD = (c->AD + c->Y) & 0xFF;
            c->IR = c->opcode;
            break;

        // ABS: absolute
        case ADDR_SEQ_BASE + ADDR_ABS + 0:  // ABS cycle 1
            BUS_READ(c->PC++);
            c->AD = BUS_DATA();
            break;
        case ADDR_SEQ_BASE + ADDR_ABS + 1:  // ABS cycle 2
            BUS_READ(c->PC++);
            c->AD |= BUS_DATA() << 8;
            break;
        case ADDR_SEQ_BASE + ADDR_ABS + 2:  // ABS cycle 3
            c->IR = c->opcode;
            break;

        // ABX: absolute,X
        case ADDR_SEQ_BASE + ADDR_ABX + 0:  // ABX cycle 1
            BUS_READ(c->PC++);
            c->AD = BUS_DATA();
            break;
        case ADDR_SEQ_BASE + ADDR_ABX + 1:  // ABX cycle 2
            BUS_READ(c->PC++);
            c->AD |= BUS_DATA() << 8;
            break;
        case ADDR_SEQ_BASE + ADDR_ABX + 2:  // ABX cycle 3
            BUS_READ((c->AD & 0xFF00) | ((c->AD + c->X) & 0xFF));
            c->IR += (~((c->AD >> 8) - ((c->AD + c->X) >> 8))) & 1;
            break;
        case ADDR_SEQ_BASE + ADDR_ABX + 3:  // ABX cycle 4
            c->AD += c->X;
            c->IR = c->opcode;
            break;

        // ABX: absolute,X (write - always takes extra cycle)
        case ADDR_SEQ_BASE + ADDR_ABX_W + 0:  // ABX cycle 1
            BUS_READ(c->PC++);
            c->AD = BUS_DATA();
            break;
        case ADDR_SEQ_BASE + ADDR_ABX_W + 1:  // ABX cycle 2
            BUS_READ(c->PC++);
            c->AD |= BUS_DATA() << 8;
            break;
        case ADDR_SEQ_BASE + ADDR_ABX_W + 2:  // ABX cycle 3
            BUS_READ((c->AD & 0xFF00) | ((c->AD + c->X) & 0xFF));
            break;
        case ADDR_SEQ_BASE + ADDR_ABX_W + 3:  // ABX cycle 4
            c->AD += c->X;
            c->IR = c->opcode;
            break;

        // ABY: absolute,Y
        case ADDR_SEQ_BASE + ADDR_ABY + 0:  // ABY cycle 1
            BUS_READ(c->PC++);
            c->AD = BUS_DATA();
            break;
        case ADDR_SEQ_BASE + ADDR_ABY + 1:  // ABY cycle 2
            BUS_READ(c->PC++);
            c->AD |= BUS_DATA() << 8;
            break;
        case ADDR_SEQ_BASE + ADDR_ABY + 2:  // ABY cycle 3
            BUS_READ((c->AD & 0xFF00) | ((c->AD + c->Y) & 0xFF));
            c->IR += (~((c->AD >> 8) - ((c->AD + c->Y) >> 8))) & 1;
            break;
        case ADDR_SEQ_BASE + ADDR_ABY + 3:  // ABY cycle 4
            c->AD += c->Y;
            c->IR = c->opcode;
            break;

        // ABY: absolute,Y (write - always takes extra cycle)
        case ADDR_SEQ_BASE + ADDR_ABY_W + 0:  // ABY cycle 1
            BUS_READ(c->PC++);
            c->AD = BUS_DATA();
            break;
        case ADDR_SEQ_BASE + ADDR_ABY_W + 1:  // ABY cycle 2
            BUS_READ(c->PC++);
            c->AD |= BUS_DATA() << 8;
            break;
        case ADDR_SEQ_BASE + ADDR_ABY_W + 2:  // ABY cycle 3
            BUS_READ((c->AD & 0xFF00) | ((c->AD + c->Y) & 0xFF));
            break;
        case ADDR_SEQ_BASE + ADDR_ABY_W + 3:  // ABY cycle 4
            c->AD += c->Y;
            c->IR = c->opcode;
            break;

        // IDX: indexed indirect (zp,X)
        case ADDR_SEQ_BASE + ADDR_IDX + 0:  // IDX cycle 1
            BUS_READ(c->PC++);
            break;
        case ADDR_SEQ_BASE + ADDR_IDX + 1:  // IDX cycle 2
            c->AD = BUS_DATA();
            BUS_INTERNAL(c->AD);
            break;
        case ADDR_SEQ_BASE + ADDR_IDX + 2:  // IDX cycle 3
            c->AD = (c->AD + c->X) & 0xFF;
            BUS_READ(c->AD);
            break;
        case ADDR_SEQ_BASE + ADDR_IDX + 3:  // IDX cycle 4
            BUS_READ((c->AD + 1) & 0xFF);
            c->AD = BUS_DATA();
            break;
        case ADDR_SEQ_BASE + ADDR_IDX + 4:  // IDX cycle 5
            c->AD |= BUS_DATA() << 8;
            c->IR = c->opcode;
            break;

        // IDY: indirect indexed (zp),Y
        case ADDR_SEQ_BASE + ADDR_IDY + 0:  // IDY cycle 1
            BUS_READ(c->PC++);
            break;
        case ADDR_SEQ_BASE + ADDR_IDY + 1:  // IDY cycle 2
            c->AD = BUS_DATA();
            BUS_READ(c->AD);
            break;
        case ADDR_SEQ_BASE + ADDR_IDY + 2:  // IDY cycle 3
            BUS_READ((c->AD + 1) & 0xFF);
            c->AD = BUS_DATA();
            break;
        case ADDR_SEQ_BASE + ADDR_IDY + 3:  // IDY cycle 4
            c->AD |= BUS_DATA() << 8;
            BUS_READ((c->AD & 0xFF00) | ((c->AD + c->Y) & 0xFF));
            c->IR += (~((c->AD >> 8) - ((c->AD + c->Y) >> 8))) & 1;
            break;
        case ADDR_SEQ_BASE + ADDR_IDY + 4:  // IDY cycle 5
            c->AD += c->Y;
            c->IR = c->opcode;
            break;

        // IDY: indirect indexed (zp),Y (write - always takes extra cycle)
        case ADDR_SEQ_BASE + ADDR_IDY_W + 0:  // IDY cycle 1
            BUS_READ(c->PC++);
            break;
        case ADDR_SEQ_BASE + ADDR_IDY_W + 1:  // IDY cycle 2
            c->AD = BUS_DATA();
            BUS_READ(c->AD);
            break;
        case ADDR_SEQ_BASE + ADDR_IDY_W + 2:  // IDY cycle 3
            BUS_READ((c->AD + 1) & 0xFF);
            c->AD = BUS_DATA();
            break;
        case ADDR_SEQ_BASE + ADDR_IDY_W + 3:  // IDY cycle 4
            c->AD |= BUS_DATA() << 8;
            BUS_READ((c->AD & 0xFF00) | ((c->AD + c->Y) & 0xFF));
            break;
        case ADDR_SEQ_BASE + ADDR_IDY_W + 4:  // IDY cycle 5
            c->AD += c->Y;
            c->IR = c->opcode;
            break;

        // ==========================================
        // [299+] SHARED CONTINUATIONS
        // ==========================================

        // BRK continuation
        case C_BRK + 0:
            BUS_WRITE(0x0100 | c->S--, c->P | FAM65XX_XF);
            if (c->brk_flags & FAM65XX_BRK_RESET) {
            	c->AD = 0xFFFC;
            } else {
            	if (c->brk_flags & FAM65XX_BRK_NMI) {
            		c->AD = 0xFFFA;
            	} else {
            		c->AD = 0xFFFE;
            	}
            };
            break;
        case C_BRK + 1:
            BUS_READ(c->AD++);
            c->P |= (FAM65XX_IF | FAM65XX_BF);
            c->brk_flags = 0;
            break;
        case C_BRK + 2:
            BUS_READ(c->AD);
            c->AD = BUS_DATA();
            break;
        case C_BRK + 3:
            c->PC = (BUS_DATA() << 8) | c->AD;
            _FETCH();
            break;

        // SLO_RMW continuation
        case C_SLO_RMW + 0:
            BUS_WRITE(c->AD, c->AD);
            break;
        case C_SLO_RMW + 1:
            c->AD = _fam65xx_asl(c, c->AD);
            c->A |= c->AD;
            _NZ(c->A);
            break;
        case C_SLO_RMW + 2:
            BUS_WRITE(c->AD, c->AD);
            _FETCH();
            break;

        // ASL_RMW continuation
        case C_ASL_RMW + 0:
            BUS_WRITE(c->AD, c->AD);
            break;
        case C_ASL_RMW + 1:
            c->AD = _fam65xx_asl(c, c->AD);
            break;
        case C_ASL_RMW + 2:
            BUS_WRITE(c->AD, c->AD);
            _FETCH();
            break;

        // BRANCH_TAKEN continuation
        case C_BRANCH_TAKEN + 0:
            BUS_INTERNAL((c->PC & 0xFF00) | (c->AD & 0xFF));
            if((c->AD & 0xFF00) == (c->PC & 0xFF00))
            {
            	c->PC = c->AD;
            	c->irq_pip >>= 1;
            	c->nmi_pip >>= 1;
            	_FETCH();
            };
            break;
        case C_BRANCH_TAKEN + 1:
            c->PC = c->AD;
            _FETCH();
            break;

        // JSR continuation
        case C_JSR + 0:
            BUS_INTERNAL(0x0100 | c->S);
            break;
        case C_JSR + 1:
            BUS_WRITE(0x0100 | c->S--, c->PC >> 8);
            break;
        case C_JSR + 2:
            BUS_WRITE(0x0100 | c->S--, c->PC);
            break;
        case C_JSR + 3:
            BUS_READ(c->PC);
            break;
        case C_JSR + 4:
            c->PC = (BUS_DATA() << 8) | c->AD;
            _FETCH();
            break;

        // RLA_RMW continuation
        case C_RLA_RMW + 0:
            BUS_WRITE(c->AD, c->AD);
            break;
        case C_RLA_RMW + 1:
            c->AD = _fam65xx_rol(c, c->AD);
            c->A &= c->AD;
            _NZ(c->A);
            break;
        case C_RLA_RMW + 2:
            BUS_WRITE(c->AD, c->AD);
            _FETCH();
            break;

        // ROL_RMW continuation
        case C_ROL_RMW + 0:
            BUS_WRITE(c->AD, c->AD);
            break;
        case C_ROL_RMW + 1:
            c->AD = _fam65xx_rol(c, c->AD);
            break;
        case C_ROL_RMW + 2:
            BUS_WRITE(c->AD, c->AD);
            _FETCH();
            break;

        // PLP continuation
        case C_PLP + 0:
            BUS_READ(0x0100 | c->S);
            break;
        case C_PLP + 1:
            c->P = (BUS_DATA() | FAM65XX_BF) & ~FAM65XX_XF;
            _FETCH();
            break;

        // RTI continuation
        case C_RTI + 0:
            BUS_READ(0x0100 | c->S++);
            break;
        case C_RTI + 1:
            BUS_READ(0x0100 | c->S++);
            c->P = (BUS_DATA() | FAM65XX_BF) & ~FAM65XX_XF;
            break;
        case C_RTI + 2:
            BUS_READ(0x0100 | c->S);
            c->AD = BUS_DATA();
            break;
        case C_RTI + 3:
            c->PC = (BUS_DATA() << 8) | c->AD;
            _FETCH();
            break;

        // SRE_RMW continuation
        case C_SRE_RMW + 0:
            BUS_WRITE(c->AD, c->AD);
            break;
        case C_SRE_RMW + 1:
            c->AD = _fam65xx_lsr(c, c->AD);
            c->A ^= c->AD;
            _NZ(c->A);
            break;
        case C_SRE_RMW + 2:
            BUS_WRITE(c->AD, c->AD);
            _FETCH();
            break;

        // LSR_RMW continuation
        case C_LSR_RMW + 0:
            BUS_WRITE(c->AD, c->AD);
            break;
        case C_LSR_RMW + 1:
            c->AD = _fam65xx_lsr(c, c->AD);
            break;
        case C_LSR_RMW + 2:
            BUS_WRITE(c->AD, c->AD);
            _FETCH();
            break;

        // JMP_ABS continuation
        case C_JMP_ABS + 0:
            BUS_READ(c->PC++);
            c->AD |= BUS_DATA() << 8;
            break;
        case C_JMP_ABS + 1:
            c->PC = c->AD;
            _FETCH();
            break;

        // RTS continuation
        case C_RTS + 0:
            BUS_READ(0x0100 | c->S++);
            break;
        case C_RTS + 1:
            BUS_READ(0x0100 | c->S);
            c->AD = BUS_DATA();
            break;
        case C_RTS + 2:
            c->PC = (BUS_DATA() << 8) | c->AD;
            break;
        case C_RTS + 3:
            BUS_READ(c->PC++);
            _FETCH();
            break;

        // RRA_RMW continuation
        case C_RRA_RMW + 0:
            BUS_WRITE(c->AD, c->AD);
            break;
        case C_RRA_RMW + 1:
            c->AD = _fam65xx_ror(c, c->AD);
            _fam65xx_adc(c, c->AD);
            break;
        case C_RRA_RMW + 2:
            BUS_WRITE(c->AD, c->AD);
            _FETCH();
            break;

        // ROR_RMW continuation
        case C_ROR_RMW + 0:
            BUS_WRITE(c->AD, c->AD);
            break;
        case C_ROR_RMW + 1:
            c->AD = _fam65xx_ror(c, c->AD);
            break;
        case C_ROR_RMW + 2:
            BUS_WRITE(c->AD, c->AD);
            _FETCH();
            break;

        // PLA continuation
        case C_PLA + 0:
            BUS_READ(0x0100 | c->S);
            break;
        case C_PLA + 1:
            c->A = BUS_DATA();
            _NZ(c->A);
            _FETCH();
            break;

        // JMP_IND continuation
        case C_JMP_IND + 0:
            BUS_READ(c->PC++);
            c->AD |= BUS_DATA() << 8;
            break;
        case C_JMP_IND + 1:
            BUS_READ(c->AD);
            break;
        case C_JMP_IND + 2:
            BUS_READ((c->AD & 0xFF00) | ((c->AD + 1) & 0xFF));
            c->AD = BUS_DATA();
            break;
        case C_JMP_IND + 3:
            c->PC = (BUS_DATA() << 8) | c->AD;
            _FETCH();
            break;

        // DCP_RMW continuation
        case C_DCP_RMW + 0:
            BUS_WRITE(c->AD, c->AD);
            break;
        case C_DCP_RMW + 1:
            c->AD--;
            _fam65xx_cmp(c, c->A, c->AD);
            break;
        case C_DCP_RMW + 2:
            BUS_WRITE(c->AD, c->AD);
            _FETCH();
            break;

        // DEC_RMW continuation
        case C_DEC_RMW + 0:
            BUS_WRITE(c->AD, c->AD);
            break;
        case C_DEC_RMW + 1:
            c->AD--;
            _NZ(c->AD);
            break;
        case C_DEC_RMW + 2:
            BUS_WRITE(c->AD, c->AD);
            _FETCH();
            break;

        // ISC_RMW continuation
        case C_ISC_RMW + 0:
            BUS_WRITE(c->AD, c->AD);
            break;
        case C_ISC_RMW + 1:
            c->AD++;
            _fam65xx_sbc(c, c->AD);
            break;
        case C_ISC_RMW + 2:
            BUS_WRITE(c->AD, c->AD);
            _FETCH();
            break;

        // INC_RMW continuation
        case C_INC_RMW + 0:
            BUS_WRITE(c->AD, c->AD);
            break;
        case C_INC_RMW + 1:
            c->AD++;
            _NZ(c->AD);
            break;
        case C_INC_RMW + 2:
            BUS_WRITE(c->AD, c->AD);
            _FETCH();
            break;

    }
    c->IR++;
    return pins;
}
